/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/auth/login/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Log in with an email and password */
    post: operations["v1_auth_login_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/logout/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Log out of the current session */
    post: operations["v1_auth_logout_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/password-reset/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Request a password reset */
    post: operations["v1_auth_password_reset_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/password-reset/confirm/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Reset a password */
    post: operations["v1_auth_password_reset_confirm_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/register/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Register a Submitter */
    post: operations["v1_auth_register_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/session/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Inspect the browser session */
    get: operations["v1_auth_session_retrieve"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/verify-email/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Verify a Submitter email address */
    post: operations["v1_auth_verify_email_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/catalog/locations/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Autocomplete reviewed Tehran locations */
    get: operations["v1_catalog_locations_list"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/catalog/properties/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Search Properties with an Active Listing */
    get: operations["v1_catalog_properties_list"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/catalog/properties/{property_id}/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a publicly available Property */
    get: operations["v1_catalog_properties_retrieve"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/system/live/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Check process liveness */
    get: operations["v1_system_live_retrieve"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/system/ready/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Check dependency readiness */
    get: operations["v1_system_ready_retrieve"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/users/me/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get the current user */
    get: operations["v1_users_me_retrieve"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * @description * `IRR` - IRR
     * @enum {string}
     */
    CurrencyEnum: "IRR";
    Detail: {
      detail: string;
    };
    /**
     * @description * `unknown` - نامشخص
     *     * `present` - دارد
     *     * `absent` - ندارد
     * @enum {string}
     */
    FeatureStateEnum: "unknown" | "present" | "absent";
    Features: {
      parking: components["schemas"]["FeatureStateEnum"];
      elevator: components["schemas"]["FeatureStateEnum"];
      storage: components["schemas"]["FeatureStateEnum"];
      balcony: components["schemas"]["FeatureStateEnum"];
      furnished: components["schemas"]["FeatureStateEnum"];
    };
    Health: {
      status: components["schemas"]["StatusEnum"];
    };
    /**
     * @description * `city` - city
     *     * `district` - district
     *     * `neighborhood` - neighborhood
     * @enum {string}
     */
    KindEnum: "city" | "district" | "neighborhood";
    ListingPublic: {
      /** Format: uuid */
      id: string;
      source: components["schemas"]["SourcePublic"];
      rental_terms: components["schemas"]["RentalTermsPublic"];
      description: string;
      source_claims: unknown;
      external_url: string;
      is_negotiable: boolean;
      is_convertible: boolean;
      /** Format: date-time */
      availability_confirmed_at: string;
      /** Format: date-time */
      available_until: string;
    };
    Location: {
      city: string;
      district: string;
      district_number: number;
      neighborhood: string;
    };
    LocationSuggestion: {
      /** Format: uuid */
      id: string;
      kind: components["schemas"]["KindEnum"];
      name: string;
      label: string;
    };
    Login: {
      /** Format: email */
      email: string;
      password: string;
    };
    /**
     * @description * `direct_contact` - تماس مستقیم
     *     * `external_link` - پیوند منبع
     *     * `disabled` - غیرفعال
     * @enum {string}
     */
    OutboundPolicyEnum: "direct_contact" | "external_link" | "disabled";
    PaginatedPropertySummaryList: {
      /** @example 123 */
      count: number;
      /**
       * Format: uri
       * @example http://api.example.org/properties/?page=2
       */
      next?: string | null;
      /**
       * Format: uri
       * @example http://api.example.org/properties/?page=1
       */
      previous?: string | null;
      results: components["schemas"]["PropertySummary"][];
    };
    PasswordResetConfirm: {
      token: string;
      new_password: string;
    };
    PasswordResetRequest: {
      /** Format: email */
      email: string;
    };
    Problem: {
      /** Format: uri */
      type: string;
      title: string;
      status: number;
      detail: string;
      code: string;
      /** Format: uuid */
      request_id: string | null;
      errors?: {
        [key: string]: components["schemas"]["ProblemFieldError"][];
      };
    };
    ProblemFieldError: {
      code: string;
      message: string;
    };
    PropertyDetail: {
      /** Format: uuid */
      id: string;
      title: string;
      canonical_slug: string;
      location: components["schemas"]["Location"];
      property_type: components["schemas"]["PropertyTypeEnum"];
      property_type_label: string;
      area_sqm: number;
      room_count: number;
      construction_year: number | null;
      floor: number | null;
      total_floors: number | null;
      units_per_floor: number | null;
      heating: string;
      cooling: string;
      features: components["schemas"]["Features"];
      listings: components["schemas"]["ListingPublic"][];
    };
    PropertySummary: {
      /** Format: uuid */
      id: string;
      title: string;
      canonical_slug: string;
      readonly location: components["schemas"]["Location"];
      property_type: components["schemas"]["PropertyTypeEnum"];
      property_type_label: string;
      area_sqm: number;
      room_count: number;
      construction_year: number | null;
      listing_count: number;
      readonly rental_terms: components["schemas"]["RentalTermsPublic"];
      /** Format: date-time */
      availability_confirmed_at: string;
    };
    /**
     * @description * `apartment` - آپارتمان
     *     * `house` - خانه
     *     * `villa` - ویلا
     * @enum {string}
     */
    PropertyTypeEnum: "apartment" | "house" | "villa";
    Registration: {
      /** Format: email */
      email: string;
      password: string;
    };
    RentalTermsPublic: {
      deposit_rial: number;
      monthly_rent_rial: number;
      currency: components["schemas"]["CurrencyEnum"];
      deposit_toman: number;
      monthly_rent_toman: number;
    };
    Session: {
      authenticated: boolean;
      csrf_token: string;
    };
    SourcePublic: {
      /** Format: uuid */
      id: string;
      name: string;
      display_name: string;
      outbound_policy: components["schemas"]["OutboundPolicyEnum"];
    };
    /**
     * @description * `ok` - ok
     *     * `unavailable` - unavailable
     * @enum {string}
     */
    StatusEnum: "ok" | "unavailable";
    Token: {
      token: string;
    };
    User: {
      /** Format: uuid */
      readonly id: string;
      /** Format: email */
      readonly email: string;
      readonly first_name: string;
      readonly last_name: string;
      readonly email_verified: boolean;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  v1_auth_login_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Login"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
      /** @description Request validation failed */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Authentication failed */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Authentication or CSRF verification failed */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Only JSON request bodies are supported */
      415: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Request was throttled */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  v1_auth_logout_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Detail"];
        };
      };
      /** @description Authentication failed */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Authentication or CSRF verification failed */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  v1_auth_password_reset_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PasswordResetRequest"];
      };
    };
    responses: {
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Detail"];
        };
      };
      /** @description Request validation failed */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Authentication or CSRF verification failed */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Only JSON request bodies are supported */
      415: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Request was throttled */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  v1_auth_password_reset_confirm_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PasswordResetConfirm"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Detail"];
        };
      };
      /** @description Request validation failed */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Authentication or CSRF verification failed */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Only JSON request bodies are supported */
      415: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Request was throttled */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  v1_auth_register_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Registration"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Detail"];
        };
      };
      /** @description Request validation failed */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Authentication or CSRF verification failed */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Only JSON request bodies are supported */
      415: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Request was throttled */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  v1_auth_session_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Session"];
        };
      };
    };
  };
  v1_auth_verify_email_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Token"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Detail"];
        };
      };
      /** @description Request validation failed */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Authentication or CSRF verification failed */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Only JSON request bodies are supported */
      415: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Request was throttled */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  v1_catalog_locations_list: {
    parameters: {
      query?: {
        /** @description Persian city, municipal district, or neighborhood name */
        q?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LocationSuggestion"][];
        };
      };
    };
  };
  v1_catalog_properties_list: {
    parameters: {
      query?: {
        area_max?: number;
        area_min?: number;
        /**
         * @description * `present` - present
         *     * `absent` - absent
         */
        balcony?: "present" | "absent";
        deposit_max_toman?: number;
        deposit_min_toman?: number;
        /**
         * @description * `present` - present
         *     * `absent` - absent
         */
        elevator?: "present" | "absent";
        /**
         * @description * `present` - present
         *     * `absent` - absent
         */
        furnished?: "present" | "absent";
        location?: string;
        monthly_rent_max_toman?: number;
        monthly_rent_min_toman?: number;
        /**
         * @description * `freshness` - freshness
         *     * `monthly_rent` - monthly_rent
         *     * `deposit` - deposit
         *     * `area` - area
         */
        ordering?: "freshness" | "monthly_rent" | "deposit" | "area";
        page?: number;
        /**
         * @description * `present` - present
         *     * `absent` - absent
         */
        parking?: "present" | "absent";
        /**
         * @description * `apartment` - آپارتمان
         *     * `house` - خانه
         *     * `villa` - ویلا
         */
        property_type?: "apartment" | "house" | "villa";
        room_count?: number;
        /**
         * @description * `present` - present
         *     * `absent` - absent
         */
        storage?: "present" | "absent";
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PaginatedPropertySummaryList"];
        };
      };
    };
  };
  v1_catalog_properties_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        property_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PropertyDetail"];
        };
      };
      /** @description No Property with an Active Listing was found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  v1_system_live_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Health"];
        };
      };
    };
  };
  v1_system_ready_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Health"];
        };
      };
      /** @description A dependency is unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Health"];
        };
      };
    };
  };
  v1_users_me_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
      /** @description Authentication is required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
}
