# Generated by Django 6.1 on 2026-08-23 06:53

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("general", "راهنمایی و پرسش"),
                            ("account_deletion", "درخواست حذف حساب"),
                            ("public_contact_removal", "حذف فوری اطلاعات تماس عمومی"),
                        ],
                        max_length=32,
                    ),
                ),
                ("message", models.TextField(max_length=4000)),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("unclassified", "دسته\u200cبندی\u200cنشده"),
                            ("guidance", "راهنمایی"),
                            ("privacy", "حریم خصوصی"),
                            ("account_deletion", "حذف حساب"),
                            ("spam", "هرزنامه"),
                        ],
                        default="unclassified",
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "باز"),
                            ("in_progress", "در حال بررسی"),
                            ("resolved", "رسیدگی\u200cشده"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("operator_note", models.TextField(blank=True, max_length=1000)),
                ("resolved_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_contact_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contact_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
