# Generated by Django 6.1 on 2026-09-17 17:56

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "intake_kind",
                    models.CharField(
                        choices=[
                            ("general", "راهنمایی و پرسش"),
                            ("account_deletion", "درخواست حذف حساب"),
                            ("public_contact_removal", "حذف فوری اطلاعات تماس عمومی"),
                        ],
                        db_column="kind",
                        editable=False,
                        max_length=32,
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=120)),
                ("message", models.TextField(max_length=4000)),
                ("requester_read_at", models.DateTimeField(blank=True, editable=False, null=True)),
                (
                    "public_updated_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("account_linked_at_intake", models.BooleanField(default=False, editable=False)),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("unclassified", "دسته\u200cبندی\u200cنشده"),
                            ("guidance", "راهنمایی"),
                            ("privacy", "حریم خصوصی"),
                            ("account_deletion", "حذف حساب"),
                            ("spam", "هرزنامه"),
                        ],
                        db_index=True,
                        default="unclassified",
                        max_length=24,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("normal", "عادی"), ("urgent", "فوری")],
                        db_index=True,
                        default="normal",
                        max_length=8,
                    ),
                ),
                ("priority_locked", models.BooleanField(default=False, editable=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "باز"),
                            ("in_progress", "در حال بررسی"),
                            ("escalated", "ارجاع\u200cشده"),
                            ("resolved", "رسیدگی\u200cشده"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=16,
                    ),
                ),
                ("operator_note", models.TextField(blank=True, max_length=1000)),
                ("escalation_destination", models.CharField(blank=True, max_length=120)),
                (
                    "required_capability",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("handle_support", "General Support handling"),
                            ("handle_privacy_requests", "Privacy Support handling"),
                        ],
                        max_length=40,
                    ),
                ),
                ("assigned_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, editable=False, null=True)),
                (
                    "resolution_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("answered_externally", "پاسخ بیرون از TorobRent"),
                            ("action_completed", "اقدام تکمیل شد"),
                            ("duplicate", "تکراری"),
                            ("spam", "هرزنامه"),
                            ("no_action_required", "بدون اقدام لازم"),
                        ],
                        editable=False,
                        max_length=24,
                        null=True,
                    ),
                ),
                (
                    "resolution_summary",
                    models.TextField(blank=True, editable=False, max_length=1000),
                ),
                (
                    "personal_content_redacted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_support_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_support_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="support_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Support Request",
                "verbose_name_plural": "Support Requests",
                "db_table": "contact_contactmessage",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="SupportPrivacyAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("defensive_contact_removal", "حذف دفاعی اطلاعات تماس عمومی"),
                            ("permanent_account_action", "اقدام دائمی حساب"),
                        ],
                        max_length=32,
                    ),
                ),
                ("completed_at", models.DateTimeField()),
                ("summary", models.TextField(max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="support_privacy_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "support_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="privacy_actions",
                        to="contact.supportrequest",
                    ),
                ),
            ],
            options={
                "ordering": ("completed_at", "created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="SupportMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "author_kind",
                    models.CharField(
                        choices=[("requester", "Requester"), ("operator", "Operator")],
                        max_length=12,
                    ),
                ),
                ("is_initial", models.BooleanField(default=False, editable=False)),
                ("body", models.TextField(max_length=2000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(blank=True, editable=False, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="support_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "support_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="messages",
                        to="contact.supportrequest",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="SupportIdentityVerification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[("out_of_band", "تأیید خارج از TorobRent")], max_length=16
                    ),
                ),
                ("verified_at", models.DateTimeField()),
                ("summary", models.TextField(max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="support_identity_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "support_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="identity_verifications",
                        to="contact.supportrequest",
                    ),
                ),
            ],
            options={
                "ordering": ("verified_at", "created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="SupportExternalContact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "ایمیل"),
                            ("phone", "تلفن"),
                            ("in_person", "حضوری"),
                            ("other", "سایر"),
                        ],
                        max_length=16,
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                ("outcome", models.CharField(max_length=120)),
                ("summary", models.TextField(max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="support_external_contacts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "support_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="external_contacts",
                        to="contact.supportrequest",
                    ),
                ),
            ],
            options={
                "ordering": ("occurred_at", "created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="SupportRequestEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("requester_initiated", models.BooleanField(default=False, editable=False)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("assigned", "واگذار شد"),
                            ("classified", "دسته\u200cبندی شد"),
                            ("escalated", "ارجاع شد"),
                            ("priority_changed", "فوریت تغییر یافت"),
                            ("reassigned", "دوباره واگذار شد"),
                            ("released", "آزاد شد"),
                            ("note_added", "یادداشت افزوده شد"),
                            ("external_contact_recorded", "ارتباط بیرونی ثبت شد"),
                            ("resolved", "رسیدگی نهایی شد"),
                            ("reopened", "دوباره باز شد"),
                            ("identity_verified", "هویت تأیید شد"),
                            ("privacy_action_recorded", "اقدام حریم خصوصی ثبت شد"),
                            ("personal_content_redacted", "محتوای شخصی حذف شد"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "prior_state",
                    models.CharField(
                        choices=[
                            ("open", "باز"),
                            ("in_progress", "در حال بررسی"),
                            ("escalated", "ارجاع\u200cشده"),
                            ("resolved", "رسیدگی\u200cشده"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "new_state",
                    models.CharField(
                        choices=[
                            ("open", "باز"),
                            ("in_progress", "در حال بررسی"),
                            ("escalated", "ارجاع\u200cشده"),
                            ("resolved", "رسیدگی\u200cشده"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("unclassified", "دسته\u200cبندی\u200cنشده"),
                            ("guidance", "راهنمایی"),
                            ("privacy", "حریم خصوصی"),
                            ("account_deletion", "حذف حساب"),
                            ("spam", "هرزنامه"),
                        ],
                        default="unclassified",
                        max_length=24,
                    ),
                ),
                (
                    "prior_classification",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("unclassified", "دسته\u200cبندی\u200cنشده"),
                            ("guidance", "راهنمایی"),
                            ("privacy", "حریم خصوصی"),
                            ("account_deletion", "حذف حساب"),
                            ("spam", "هرزنامه"),
                        ],
                        max_length=24,
                        null=True,
                    ),
                ),
                (
                    "new_classification",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("unclassified", "دسته\u200cبندی\u200cنشده"),
                            ("guidance", "راهنمایی"),
                            ("privacy", "حریم خصوصی"),
                            ("account_deletion", "حذف حساب"),
                            ("spam", "هرزنامه"),
                        ],
                        max_length=24,
                        null=True,
                    ),
                ),
                (
                    "prior_priority",
                    models.CharField(
                        blank=True,
                        choices=[("normal", "عادی"), ("urgent", "فوری")],
                        max_length=8,
                        null=True,
                    ),
                ),
                (
                    "new_priority",
                    models.CharField(
                        blank=True,
                        choices=[("normal", "عادی"), ("urgent", "فوری")],
                        max_length=8,
                        null=True,
                    ),
                ),
                ("escalation_destination", models.CharField(blank=True, max_length=120)),
                (
                    "required_capability",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("handle_support", "General Support handling"),
                            ("handle_privacy_requests", "Privacy Support handling"),
                        ],
                        max_length=40,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                (
                    "resolution_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("answered_externally", "پاسخ بیرون از TorobRent"),
                            ("action_completed", "اقدام تکمیل شد"),
                            ("duplicate", "تکراری"),
                            ("spam", "هرزنامه"),
                            ("no_action_required", "بدون اقدام لازم"),
                        ],
                        max_length=24,
                        null=True,
                    ),
                ),
                ("resolution_summary", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="support_request_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "new_assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="support_request_events_reassigned_to",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prior_assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="support_request_events_reassigned_from",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "support_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="contact.supportrequest",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="SupportRequestNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("body", models.TextField(max_length=2000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="support_request_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "corrects_note",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="corrections",
                        to="contact.supportrequestnote",
                    ),
                ),
                (
                    "support_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notes",
                        to="contact.supportrequest",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.AddIndex(
            model_name="supportrequest",
            index=models.Index(fields=["intake_kind"], name="support_intake_kind_idx"),
        ),
        migrations.AddConstraint(
            model_name="supportrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("assigned_at__isnull", True), ("assignee__isnull", True)),
                    models.Q(("assigned_at__isnull", False), ("assignee__isnull", False)),
                    _connector="OR",
                ),
                name="support_assignment_fields_together",
            ),
        ),
        migrations.AddConstraint(
            model_name="supportmessage",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("author_kind", "requester"), ("author__isnull", False), _connector="OR"
                ),
                name="operator_support_message_requires_author",
            ),
        ),
        migrations.AddConstraint(
            model_name="supportmessage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_initial", True)),
                fields=("support_request",),
                name="one_initial_message_per_support_request",
            ),
        ),
        migrations.AddConstraint(
            model_name="supportrequestevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("event_type", "reopened"), ("requester_initiated", True)),
                    ("actor__isnull", False),
                    _connector="OR",
                ),
                name="operational_support_event_requires_actor",
            ),
        ),
    ]
