# Generated by Django 6.1 on 2026-08-25

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_contact_message_permissions(apps, schema_editor):
    Permission = apps.get_model("auth", "Permission")
    for action in ("add", "change", "delete", "view"):
        old_permission = Permission.objects.filter(
            content_type__app_label="contact",
            codename=f"{action}_contactmessage",
        ).first()
        if old_permission is None:
            continue
        new_permission, _ = Permission.objects.get_or_create(
            content_type=old_permission.content_type,
            codename=f"{action}_supportrequest",
            defaults={"name": f"Can {action} Support Request"},
        )
        new_permission.user_set.add(*old_permission.user_set.all())
        new_permission.group_set.add(*old_permission.group_set.all())


def restore_contact_message_permissions(apps, schema_editor):
    Permission = apps.get_model("auth", "Permission")
    for action in ("add", "change", "delete", "view"):
        new_permission = Permission.objects.filter(
            content_type__app_label="contact",
            codename=f"{action}_supportrequest",
        ).first()
        if new_permission is None:
            continue
        old_permission, _ = Permission.objects.get_or_create(
            content_type=new_permission.content_type,
            codename=f"{action}_contactmessage",
            defaults={"name": f"Can {action} contact message"},
        )
        old_permission.user_set.add(*new_permission.user_set.all())
        old_permission.group_set.add(*new_permission.group_set.all())


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameModel(
                    old_name="ContactMessage",
                    new_name="SupportRequest",
                ),
                migrations.AlterModelTable(
                    name="supportrequest",
                    table="contact_contactmessage",
                ),
                migrations.RenameField(
                    model_name="supportrequest",
                    old_name="kind",
                    new_name="intake_kind",
                ),
                migrations.AlterField(
                    model_name="supportrequest",
                    name="intake_kind",
                    field=models.CharField(
                        choices=[
                            ("general", "راهنمایی و پرسش"),
                            ("account_deletion", "درخواست حذف حساب"),
                            (
                                "public_contact_removal",
                                "حذف فوری اطلاعات تماس عمومی",
                            ),
                        ],
                        db_column="kind",
                        max_length=32,
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="supportrequest",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Support Request",
                "verbose_name_plural": "Support Requests",
            },
        ),
        migrations.AlterField(
            model_name="supportrequest",
            name="classification",
            field=models.CharField(
                choices=[
                    ("unclassified", "دسته‌بندی‌نشده"),
                    ("guidance", "راهنمایی"),
                    ("privacy", "حریم خصوصی"),
                    ("account_deletion", "حذف حساب"),
                    ("spam", "هرزنامه"),
                ],
                db_index=True,
                default="unclassified",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="supportrequest",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="supportrequest",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_support_requests",
                to="accounts.user",
            ),
        ),
        migrations.AlterField(
            model_name="supportrequest",
            name="submitter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="support_requests",
                to="accounts.user",
            ),
        ),
        migrations.AlterField(
            model_name="supportrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "باز"),
                    ("in_progress", "در حال بررسی"),
                    ("resolved", "رسیدگی‌شده"),
                ],
                db_index=True,
                default="open",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="supportrequest",
            name="assigned_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="supportrequest",
            name="assignee",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_support_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="supportrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("assigned_at__isnull", True), ("assignee__isnull", True)),
                    models.Q(("assigned_at__isnull", False), ("assignee__isnull", False)),
                    _connector="OR",
                ),
                name="support_assignment_fields_together",
            ),
        ),
        migrations.AddIndex(
            model_name="supportrequest",
            index=models.Index(fields=["intake_kind"], name="support_intake_kind_idx"),
        ),
        migrations.CreateModel(
            name="SupportRequestEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[("assigned", "واگذار شد"), ("released", "آزاد شد")],
                        max_length=16,
                    ),
                ),
                (
                    "prior_state",
                    models.CharField(
                        choices=[
                            ("open", "باز"),
                            ("in_progress", "در حال بررسی"),
                            ("resolved", "رسیدگی‌شده"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "new_state",
                    models.CharField(
                        choices=[
                            ("open", "باز"),
                            ("in_progress", "در حال بررسی"),
                            ("resolved", "رسیدگی‌شده"),
                        ],
                        max_length=16,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="support_request_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "support_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="contact.supportrequest",
                    ),
                ),
            ],
            options={"ordering": ("created_at", "id")},
        ),
        migrations.RunPython(
            copy_contact_message_permissions,
            restore_contact_message_permissions,
        ),
    ]
