# Generated by Django 6.1 on 2026-08-25 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def prioritize_existing_public_contact_removal(apps, schema_editor):
    SupportRequest = apps.get_model("contact", "SupportRequest")
    SupportRequest.objects.using(schema_editor.connection.alias).filter(
        intake_kind="public_contact_removal"
    ).update(priority="urgent", priority_locked=True)


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0002_rename_support_request"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="supportrequest",
            name="escalation_destination",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="supportrequest",
            name="priority",
            field=models.CharField(
                choices=[("normal", "عادی"), ("urgent", "فوری")],
                db_index=True,
                default="normal",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="supportrequest",
            name="priority_locked",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="supportrequest",
            name="required_capability",
            field=models.CharField(
                blank=True,
                choices=[
                    ("handle_support", "General Support handling"),
                    ("handle_privacy_requests", "Privacy Support handling"),
                ],
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="supportrequestevent",
            name="escalation_destination",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="supportrequestevent",
            name="new_assignee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="support_request_events_reassigned_to",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="supportrequestevent",
            name="new_classification",
            field=models.CharField(
                blank=True,
                choices=[
                    ("unclassified", "دسته\u200cبندی\u200cنشده"),
                    ("guidance", "راهنمایی"),
                    ("privacy", "حریم خصوصی"),
                    ("account_deletion", "حذف حساب"),
                    ("spam", "هرزنامه"),
                ],
                max_length=24,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="supportrequestevent",
            name="new_priority",
            field=models.CharField(
                blank=True,
                choices=[("normal", "عادی"), ("urgent", "فوری")],
                max_length=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="supportrequestevent",
            name="prior_assignee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="support_request_events_reassigned_from",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="supportrequestevent",
            name="prior_classification",
            field=models.CharField(
                blank=True,
                choices=[
                    ("unclassified", "دسته\u200cبندی\u200cنشده"),
                    ("guidance", "راهنمایی"),
                    ("privacy", "حریم خصوصی"),
                    ("account_deletion", "حذف حساب"),
                    ("spam", "هرزنامه"),
                ],
                max_length=24,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="supportrequestevent",
            name="prior_priority",
            field=models.CharField(
                blank=True,
                choices=[("normal", "عادی"), ("urgent", "فوری")],
                max_length=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="supportrequestevent",
            name="required_capability",
            field=models.CharField(
                blank=True,
                choices=[
                    ("handle_support", "General Support handling"),
                    ("handle_privacy_requests", "Privacy Support handling"),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="supportrequest",
            name="intake_kind",
            field=models.CharField(
                choices=[
                    ("general", "راهنمایی و پرسش"),
                    ("account_deletion", "درخواست حذف حساب"),
                    ("public_contact_removal", "حذف فوری اطلاعات تماس عمومی"),
                ],
                db_column="kind",
                editable=False,
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="supportrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "باز"),
                    ("in_progress", "در حال بررسی"),
                    ("escalated", "ارجاع\u200cشده"),
                    ("resolved", "رسیدگی\u200cشده"),
                ],
                db_index=True,
                default="open",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="supportrequestevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("assigned", "واگذار شد"),
                    ("classified", "دسته\u200cبندی شد"),
                    ("escalated", "ارجاع شد"),
                    ("priority_changed", "فوریت تغییر یافت"),
                    ("reassigned", "دوباره واگذار شد"),
                    ("released", "آزاد شد"),
                ],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="supportrequestevent",
            name="new_state",
            field=models.CharField(
                choices=[
                    ("open", "باز"),
                    ("in_progress", "در حال بررسی"),
                    ("escalated", "ارجاع\u200cشده"),
                    ("resolved", "رسیدگی\u200cشده"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="supportrequestevent",
            name="prior_state",
            field=models.CharField(
                choices=[
                    ("open", "باز"),
                    ("in_progress", "در حال بررسی"),
                    ("escalated", "ارجاع\u200cشده"),
                    ("resolved", "رسیدگی\u200cشده"),
                ],
                max_length=16,
            ),
        ),
        migrations.RunPython(
            prioritize_existing_public_contact_removal,
            migrations.RunPython.noop,
        ),
    ]
