# Generated by Django 6.1 on 2026-08-25 14:26

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0003_add_privacy_aware_support_triage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="supportrequestevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("assigned", "واگذار شد"),
                    ("classified", "دسته\u200cبندی شد"),
                    ("escalated", "ارجاع شد"),
                    ("priority_changed", "فوریت تغییر یافت"),
                    ("reassigned", "دوباره واگذار شد"),
                    ("released", "آزاد شد"),
                    ("note_added", "یادداشت افزوده شد"),
                ],
                max_length=24,
            ),
        ),
        migrations.CreateModel(
            name="SupportRequestNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("body", models.TextField(max_length=2000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="support_request_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "corrects_note",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="corrections",
                        to="contact.supportrequestnote",
                    ),
                ),
                (
                    "support_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notes",
                        to="contact.supportrequest",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
    ]
