# Generated by Django 6.1 on 2026-08-25 14:28

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0004_alter_supportrequestevent_event_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="supportrequestevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("assigned", "واگذار شد"),
                    ("classified", "دسته\u200cبندی شد"),
                    ("escalated", "ارجاع شد"),
                    ("priority_changed", "فوریت تغییر یافت"),
                    ("reassigned", "دوباره واگذار شد"),
                    ("released", "آزاد شد"),
                    ("note_added", "یادداشت افزوده شد"),
                    ("external_contact_recorded", "ارتباط بیرونی ثبت شد"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="SupportExternalContact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "ایمیل"),
                            ("phone", "تلفن"),
                            ("in_person", "حضوری"),
                            ("other", "سایر"),
                        ],
                        max_length=16,
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                ("outcome", models.CharField(max_length=120)),
                ("summary", models.TextField(max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="support_external_contacts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "support_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="external_contacts",
                        to="contact.supportrequest",
                    ),
                ),
            ],
            options={
                "ordering": ("occurred_at", "created_at", "id"),
            },
        ),
    ]
