# Generated by Django 6.1 on 2026-08-25 14:30

from django.db import migrations, models


def populate_event_classification(apps, schema_editor):
    SupportRequestEvent = apps.get_model("contact", "SupportRequestEvent")
    for event in SupportRequestEvent.objects.using(schema_editor.connection.alias).select_related(
        "support_request"
    ):
        event.classification = event.new_classification or event.support_request.classification
        event.save(update_fields=("classification",))


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0005_alter_supportrequestevent_event_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportrequest",
            name="resolution_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("answered_externally", "پاسخ بیرون از TorobRent"),
                    ("action_completed", "اقدام تکمیل شد"),
                    ("duplicate", "تکراری"),
                    ("spam", "هرزنامه"),
                    ("no_action_required", "بدون اقدام لازم"),
                ],
                editable=False,
                max_length=24,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="supportrequest",
            name="resolution_summary",
            field=models.TextField(blank=True, editable=False, max_length=1000),
        ),
        migrations.AddField(
            model_name="supportrequestevent",
            name="classification",
            field=models.CharField(
                choices=[
                    ("unclassified", "دسته\u200cبندی\u200cنشده"),
                    ("guidance", "راهنمایی"),
                    ("privacy", "حریم خصوصی"),
                    ("account_deletion", "حذف حساب"),
                    ("spam", "هرزنامه"),
                ],
                default="unclassified",
                max_length=24,
            ),
        ),
        migrations.RunPython(populate_event_classification, migrations.RunPython.noop),
        migrations.AddField(
            model_name="supportrequestevent",
            name="resolution_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("answered_externally", "پاسخ بیرون از TorobRent"),
                    ("action_completed", "اقدام تکمیل شد"),
                    ("duplicate", "تکراری"),
                    ("spam", "هرزنامه"),
                    ("no_action_required", "بدون اقدام لازم"),
                ],
                max_length=24,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="supportrequestevent",
            name="resolution_summary",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="supportrequestevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("assigned", "واگذار شد"),
                    ("classified", "دسته\u200cبندی شد"),
                    ("escalated", "ارجاع شد"),
                    ("priority_changed", "فوریت تغییر یافت"),
                    ("reassigned", "دوباره واگذار شد"),
                    ("released", "آزاد شد"),
                    ("note_added", "یادداشت افزوده شد"),
                    ("external_contact_recorded", "ارتباط بیرونی ثبت شد"),
                    ("resolved", "رسیدگی نهایی شد"),
                    ("reopened", "دوباره باز شد"),
                ],
                max_length=32,
            ),
        ),
    ]
