# Generated by Django 6.1 on 2026-08-25 14:33

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preserve_authenticated_intake_link(apps, schema_editor):
    SupportRequest = apps.get_model("contact", "SupportRequest")
    SupportRequest.objects.using(schema_editor.connection.alias).filter(
        submitter__isnull=False
    ).update(account_linked_at_intake=True)


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0006_supportrequest_resolution_category_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="supportrequest",
            name="account_linked_at_intake",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.RunPython(preserve_authenticated_intake_link, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="supportrequestevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("assigned", "واگذار شد"),
                    ("classified", "دسته\u200cبندی شد"),
                    ("escalated", "ارجاع شد"),
                    ("priority_changed", "فوریت تغییر یافت"),
                    ("reassigned", "دوباره واگذار شد"),
                    ("released", "آزاد شد"),
                    ("note_added", "یادداشت افزوده شد"),
                    ("external_contact_recorded", "ارتباط بیرونی ثبت شد"),
                    ("resolved", "رسیدگی نهایی شد"),
                    ("reopened", "دوباره باز شد"),
                    ("identity_verified", "هویت تأیید شد"),
                    ("privacy_action_recorded", "اقدام حریم خصوصی ثبت شد"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="SupportIdentityVerification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[("out_of_band", "تأیید خارج از TorobRent")], max_length=16
                    ),
                ),
                ("verified_at", models.DateTimeField()),
                ("summary", models.TextField(max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="support_identity_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "support_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="identity_verifications",
                        to="contact.supportrequest",
                    ),
                ),
            ],
            options={
                "ordering": ("verified_at", "created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="SupportPrivacyAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("defensive_contact_removal", "حذف دفاعی اطلاعات تماس عمومی"),
                            ("permanent_account_action", "اقدام دائمی حساب"),
                        ],
                        max_length=32,
                    ),
                ),
                ("completed_at", models.DateTimeField()),
                ("summary", models.TextField(max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="support_privacy_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "support_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="privacy_actions",
                        to="contact.supportrequest",
                    ),
                ),
            ],
            options={
                "ordering": ("completed_at", "created_at", "id"),
            },
        ),
    ]
