# Generated by Django 6.1 on 2026-08-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0007_supportrequest_account_linked_at_intake_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportrequest",
            name="personal_content_redacted_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="supportrequestevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("assigned", "واگذار شد"),
                    ("classified", "دسته\u200cبندی شد"),
                    ("escalated", "ارجاع شد"),
                    ("priority_changed", "فوریت تغییر یافت"),
                    ("reassigned", "دوباره واگذار شد"),
                    ("released", "آزاد شد"),
                    ("note_added", "یادداشت افزوده شد"),
                    ("external_contact_recorded", "ارتباط بیرونی ثبت شد"),
                    ("resolved", "رسیدگی نهایی شد"),
                    ("reopened", "دوباره باز شد"),
                    ("identity_verified", "هویت تأیید شد"),
                    ("privacy_action_recorded", "اقدام حریم خصوصی ثبت شد"),
                    ("personal_content_redacted", "محتوای شخصی حذف شد"),
                ],
                max_length=32,
            ),
        ),
    ]
