# Generated by Django 6.1 on 2026-09-03 14:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0009_supportrequest_requester_read_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="supportmessage",
            name="is_initial",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddConstraint(
            model_name="supportmessage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_initial", True)),
                fields=("support_request",),
                name="one_initial_message_per_support_request",
            ),
        ),
    ]
