# Generated by Django 6.1 on 2026-09-03 14:24

import django.utils.timezone
from django.db import migrations, models


def preserve_latest_activity(apps, schema_editor):
    SupportRequest = apps.get_model("contact", "SupportRequest")
    for support_request in SupportRequest.objects.only("id", "updated_at").iterator():
        SupportRequest.objects.filter(id=support_request.id).update(
            public_updated_at=support_request.updated_at
        )


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0010_supportmessage_is_initial_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportrequest",
            name="public_updated_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.RunPython(preserve_latest_activity, migrations.RunPython.noop),
    ]
