# Generated by Django 6.1 on 2026-09-03 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0012_alter_supportmessage_author_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="supportrequestevent",
            name="actor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="support_request_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="supportmessage",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("author_kind", "requester"), ("author__isnull", False), _connector="OR"
                ),
                name="operator_support_message_requires_author",
            ),
        ),
        migrations.AddConstraint(
            model_name="supportrequestevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("event_type", "reopened"), ("actor__isnull", False), _connector="OR"
                ),
                name="operational_support_event_requires_actor",
            ),
        ),
    ]
