# Generated by Django 6.1 on 2026-09-03 16:50

from django.conf import settings
from django.db import migrations, models


def mark_requester_initiated_reopens(apps, schema_editor):
    support_request_event = apps.get_model("contact", "SupportRequestEvent")
    support_request_event.objects.filter(
        models.Q(actor__isnull=True) | models.Q(actor_id=models.F("support_request__submitter_id")),
        event_type="reopened",
    ).update(requester_initiated=True)


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0013_alter_supportrequestevent_actor_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="supportrequestevent",
            name="operational_support_event_requires_actor",
        ),
        migrations.AddField(
            model_name="supportrequestevent",
            name="requester_initiated",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.RunPython(
            mark_requester_initiated_reopens,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="supportrequestevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("event_type", "reopened"), ("requester_initiated", True)),
                    ("actor__isnull", False),
                    _connector="OR",
                ),
                name="operational_support_event_requires_actor",
            ),
        ),
    ]
