# Generated by Django 6.1 on 2026-09-17 17:56

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import apps.common.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("common", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalListingCandidate",
            fields=[
                (
                    "publication_outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("new", "آگهی جدید"),
                            ("updated", "به\u200cروزرسانی\u200cشده"),
                            ("unchanged", "بدون تغییر"),
                        ],
                        db_default="",
                        default="",
                        max_length=16,
                    ),
                ),
                ("requested_urls", models.JSONField(db_default=[], default=list)),
                ("structural_drift", models.BooleanField(db_default=False, default=False)),
                ("superseded", models.BooleanField(db_default=False, default=False)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("source_claims", models.JSONField(db_default={}, default=dict)),
                ("evidence", models.JSONField(db_default={}, default=dict)),
                ("conflicts", models.JSONField(db_default={}, default=dict)),
                ("validation_errors", models.JSONField(db_default={}, default=dict)),
                ("corrections", models.JSONField(db_default={}, default=dict)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار بررسی"),
                            ("changes_requested", "نیازمند اصلاح"),
                            ("rejected", "ردشده"),
                            ("published", "منتشرشده"),
                            ("cancelled", "لغوشده"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("revision", models.PositiveIntegerField(default=1, editable=False)),
                ("title", models.CharField(max_length=200)),
                ("external_url", models.URLField(max_length=1000)),
                (
                    "property_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("apartment", "آپارتمان"),
                            ("house", "خانه"),
                            ("villa", "ویلا"),
                            ("office", "دفتر اداری"),
                            ("shop", "مغازه"),
                            ("warehouse", "انبار"),
                            ("workshop", "کارگاه"),
                        ],
                        max_length=16,
                    ),
                ),
                ("area_sqm", models.PositiveIntegerField(null=True)),
                ("room_count", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("deposit_rial", models.PositiveBigIntegerField(null=True)),
                ("monthly_rent_rial", models.PositiveBigIntegerField(null=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "city",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.PROTECT, to="catalog.city"
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.district",
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="external_candidates",
                        to="catalog.listing",
                    ),
                ),
                (
                    "neighborhood",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.neighborhood",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="external_listing_candidates",
                        to="catalog.source",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="CandidateImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("original_url", models.TextField()),
                ("source_order", models.PositiveSmallIntegerField()),
                ("position", models.PositiveSmallIntegerField()),
                ("is_primary", models.BooleanField(default=False)),
                ("excluded", models.BooleanField(default=False)),
                ("state", models.CharField(default="pending", max_length=16)),
                ("failure_code", models.CharField(blank=True, max_length=64)),
                ("content_hash", models.CharField(blank=True, db_index=True, max_length=64)),
                (
                    "normalized_pixel_sha256",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("perceptual_dhash", models.CharField(blank=True, db_index=True, max_length=16)),
                ("accepted_at", models.DateTimeField(null=True)),
                ("retention_checked_at", models.DateTimeField(db_index=True, null=True)),
                ("unreferenced_at", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "accepted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accepted_external_images",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "listing_image",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="external_origin",
                        to="catalog.listingimage",
                    ),
                ),
                (
                    "property_image",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="external_origins",
                        to="catalog.propertyimage",
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="images",
                        to="source_proposals.externallistingcandidate",
                    ),
                ),
            ],
            options={
                "ordering": ("position", "source_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="ExternalListingCandidateEvent",
            fields=[
                ("corrections", models.JSONField(db_default={}, default=dict)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("revision", models.PositiveIntegerField()),
                (
                    "prior_state",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار بررسی"),
                            ("changes_requested", "نیازمند اصلاح"),
                            ("rejected", "ردشده"),
                            ("published", "منتشرشده"),
                            ("cancelled", "لغوشده"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "new_state",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار بررسی"),
                            ("changes_requested", "نیازمند اصلاح"),
                            ("rejected", "ردشده"),
                            ("published", "منتشرشده"),
                            ("cancelled", "لغوشده"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="external_listing_candidate_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="source_proposals.externallistingcandidate",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="ExternalListingCandidateReviewClaim",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("revision", models.PositiveIntegerField()),
                ("expires_at", models.DateTimeField()),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_claims",
                        to="source_proposals.externallistingcandidate",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="external_listing_candidate_review_claims",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ExtractionRequest",
            fields=[
                ("delivery_pending", models.BooleanField(db_default=False, default=False)),
                ("delivery_attempted_at", models.DateTimeField(blank=True, null=True)),
                ("delivery_error", models.TextField(blank=True, db_default="", default="")),
                ("processing_revision", models.PositiveIntegerField(db_default=0, default=0)),
                ("publication_revision", models.PositiveIntegerField(db_default=0, default=0)),
                (
                    "review_mode",
                    models.CharField(
                        choices=[("approval_required", "نیازمند تأیید"), ("automatic", "خودکار")],
                        db_default="",
                        default="",
                        max_length=24,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("submitted_url", models.URLField(max_length=1000)),
                ("canonical_url", models.URLField(max_length=1000)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("queued", "در صف"),
                            ("running", "در حال استخراج"),
                            ("complete", "پایان یافته"),
                            ("failed", "ناموفق"),
                            ("cancelled", "لغوشده"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "initiated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="initiated_extractions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="ExtractionRun",
            fields=[
                ("discovery_checkpoint", models.JSONField(db_default={}, default=dict)),
                ("discovery_generation", models.PositiveIntegerField(db_default=0, default=0)),
                (
                    "discovery_stop_reason",
                    models.CharField(db_default="", default="", max_length=32),
                ),
                ("attempted_pages", models.PositiveIntegerField(null=True)),
                ("usable_results", models.PositiveIntegerField(null=True)),
                ("skipped_pages", models.JSONField(db_default=[], default=list)),
                ("withdrawals", models.JSONField(db_default=[], default=list)),
                ("candidate_rejected", models.PositiveIntegerField(db_default=0, default=0)),
                ("revision", models.PositiveIntegerField(db_default=1, default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("pipeline_version", models.CharField(max_length=64)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("queued", "در صف"),
                            ("running", "در حال استخراج"),
                            ("complete", "پایان یافته"),
                            ("failed", "ناموفق"),
                            ("cancelled", "لغوشده"),
                        ],
                        default="running",
                        max_length=16,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=1)),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(null=True)),
                ("discovered", models.PositiveIntegerField(default=0)),
                ("extracted", models.PositiveIntegerField(default=0)),
                ("published", models.PositiveIntegerField(default=0)),
                ("needs_attention", models.PositiveIntegerField(default=0)),
                ("rejected", models.PositiveIntegerField(default=0)),
                ("failed", models.PositiveIntegerField(default=0)),
                ("errors", models.JSONField(default=list)),
                ("results", models.JSONField(default=list)),
                (
                    "request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="run",
                        to="source_proposals.extractionrequest",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="externallistingcandidate",
            name="extraction_run",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="candidates",
                to="source_proposals.extractionrun",
            ),
        ),
        migrations.CreateModel(
            name="ExtractionRunDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("revision", models.PositiveIntegerField()),
                ("candidate_ids", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decisions",
                        to="source_proposals.extractionrun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SourceAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("revoked_at", models.DateTimeField(null=True)),
                (
                    "representative",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="catalog.source",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="extractionrequest",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="requests",
                to="source_proposals.sourceassignment",
            ),
        ),
        migrations.CreateModel(
            name="SourceBulkAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("action", models.CharField(max_length=24)),
                ("exception_ids", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalog.source"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SourceExceptionNotice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("summary", "Summary"), ("failure", "Failure")], max_length=16
                    ),
                ),
                ("changes", models.JSONField(default=dict)),
                ("summary_date", models.DateField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalog.source"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SourceExceptionNotificationState",
            fields=[
                (
                    "source",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="catalog.source",
                    ),
                ),
                ("pending_changes", models.JSONField(default=dict)),
                ("last_summary_date", models.DateField(null=True)),
                ("last_delivery_check", models.DateTimeField(null=True)),
                ("failing", models.BooleanField(default=False)),
                ("failure_notified", models.BooleanField(default=False)),
                ("last_attempt", models.PositiveIntegerField(default=0)),
                (
                    "last_run",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="source_proposals.extractionrun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SourceExclusion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("exact", "Exact URL"), ("path_prefix", "Path section")],
                        max_length=16,
                    ),
                ),
                ("url", models.URLField(max_length=1000)),
                ("reason", models.CharField(max_length=2000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=apps.common.deletion.set_null_in_immutable_history,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exclusions",
                        to="catalog.source",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.AddField(
            model_name="externallistingcandidate",
            name="exclusion_hold",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="held_candidates",
                to="source_proposals.sourceexclusion",
            ),
        ),
        migrations.CreateModel(
            name="SourceExclusionAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("remove", "Remove"), ("withdraw", "Withdraw Listings")],
                        max_length=16,
                    ),
                ),
                ("reason", models.CharField(max_length=2000)),
                ("listing_ids", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=apps.common.deletion.set_null_in_immutable_history,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exclusion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="actions",
                        to="source_proposals.sourceexclusion",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="SourceExtractionException",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("canonical_url", models.URLField(max_length=1000)),
                ("first_occurrence", models.DateTimeField(null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("open", "باز"),
                            ("resolved", "رفع شده"),
                            ("excluded", "کنار گذاشته شده"),
                        ],
                        max_length=16,
                    ),
                ),
                ("problem", models.CharField(blank=True, max_length=64)),
                ("detail", models.TextField(blank=True)),
                ("last_attempt", models.PositiveIntegerField()),
                ("last_attempt_at", models.DateTimeField()),
                (
                    "last_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="source_proposals.extractionrun",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exceptions",
                        to="catalog.source",
                    ),
                ),
            ],
            options={
                "ordering": ("canonical_url",),
            },
        ),
        migrations.CreateModel(
            name="SourceExceptionAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("attempt", models.PositiveIntegerField()),
                ("attempted_at", models.DateTimeField()),
                ("state", models.CharField(max_length=16)),
                ("problem", models.CharField(blank=True, max_length=64)),
                ("detail", models.TextField(blank=True)),
                ("is_current", models.BooleanField()),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="source_proposals.extractionrun",
                    ),
                ),
                (
                    "exception",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="source_proposals.sourceextractionexception",
                    ),
                ),
            ],
            options={
                "ordering": ("-attempted_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="SourceImageHost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("host", models.CharField(max_length=253)),
                ("approved_at", models.DateTimeField(auto_now_add=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="image_hosts",
                        to="catalog.source",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SourceProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "source",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="profile",
                        to="catalog.source",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SourceProfileDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "review_mode",
                    models.CharField(
                        blank=True,
                        choices=[("approval_required", "نیازمند تأیید"), ("automatic", "خودکار")],
                        max_length=24,
                    ),
                ),
                ("limitations_acknowledged", models.BooleanField(db_default=False, default=False)),
                (
                    "representative",
                    models.ForeignKey(
                        null=True,
                        on_delete=apps.common.deletion.set_null_in_immutable_history,
                        related_name="source_profile_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="sourceassignment",
            name="approval",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assignment",
                to="source_proposals.sourceprofiledecision",
            ),
        ),
        migrations.CreateModel(
            name="SourceProfileRepair",
            fields=[
                ("id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("reviewed_revision", models.PositiveIntegerField()),
                ("selected_fields", models.JSONField()),
                ("model", models.CharField(max_length=128)),
                ("prompt_version", models.CharField(max_length=64)),
                ("schema_version", models.CharField(max_length=64)),
                ("evidence_sha256", models.CharField(max_length=64)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=apps.common.deletion.set_null_in_immutable_history,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-started_at",),
            },
        ),
        migrations.CreateModel(
            name="SourceProfileVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("rules", models.JSONField()),
                ("structural_fingerprint", models.TextField()),
                ("validation", models.JSONField()),
                ("samples", models.JSONField()),
                ("exclusions", models.JSONField()),
                ("diagnostics", models.JSONField(default=dict)),
                ("pipeline_version", models.CharField(max_length=64)),
                (
                    "provenance",
                    models.CharField(
                        choices=[
                            ("discovery", "Discovery"),
                            ("manual", "Manual"),
                            ("llm", "LLM repair"),
                        ],
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=apps.common.deletion.set_null_in_immutable_history,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="source_proposals.sourceprofileversion",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="source_proposals.sourceprofile",
                    ),
                ),
            ],
            options={
                "ordering": ("-number",),
            },
        ),
        migrations.CreateModel(
            name="SourceProfileRepairResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("outcome", models.CharField(max_length=32)),
                ("detail", models.TextField()),
                ("structured_result", models.JSONField(null=True)),
                ("validation", models.JSONField(default=dict)),
                ("finished_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("duration_ms", models.PositiveIntegerField()),
                (
                    "repair",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="result",
                        to="source_proposals.sourceprofilerepair",
                    ),
                ),
                (
                    "result_version",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="source_proposals.sourceprofileversion",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="sourceprofilerepair",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="repairs",
                to="source_proposals.sourceprofileversion",
            ),
        ),
        migrations.AddField(
            model_name="sourceprofiledecision",
            name="version",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="decision",
                to="source_proposals.sourceprofileversion",
            ),
        ),
        migrations.AddField(
            model_name="sourceprofile",
            name="active_version",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="active_profile",
                to="source_proposals.sourceprofileversion",
            ),
        ),
        migrations.AddField(
            model_name="extractionrun",
            name="profile_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="source_proposals.sourceprofileversion",
            ),
        ),
        migrations.AddField(
            model_name="extractionrequest",
            name="profile_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="source_proposals.sourceprofileversion",
            ),
        ),
        migrations.AddField(
            model_name="externallistingcandidate",
            name="discovery_version",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="media_candidates",
                to="source_proposals.sourceprofileversion",
            ),
        ),
        migrations.CreateModel(
            name="SourceProposal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "پیش\u200cنویس"),
                            ("pending", "در انتظار بررسی"),
                            ("changes_requested", "نیازمند اصلاح"),
                            ("rejected", "ردشده"),
                            ("approved", "تأییدشده"),
                            ("revoked", "تخصیص لغوشده"),
                        ],
                        default="draft",
                        max_length=24,
                    ),
                ),
                ("revision", models.PositiveIntegerField(default=1, editable=False)),
                ("responsibility_revision", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "current_step",
                    models.CharField(
                        choices=[
                            ("details", "اطلاعات وب\u200cسایت"),
                            ("preview", "بازبینی اطلاعات"),
                        ],
                        default="details",
                        max_length=16,
                    ),
                ),
                ("website_name", models.CharField(blank=True, max_length=200)),
                ("website_url", models.URLField(blank=True, max_length=1000)),
                ("normalized_domain", models.CharField(blank=True, db_index=True, max_length=253)),
                (
                    "relationship",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("website_owner", "مالک وب\u200cسایت"),
                            ("website_manager", "مدیر وب\u200cسایت"),
                            ("authorized_representative", "نماینده مجاز"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "inventory_range",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1_10", "۱ تا ۱۰"),
                            ("11_50", "۱۱ تا ۵۰"),
                            ("51_200", "۵۱ تا ۲۰۰"),
                            ("more_than_200", "بیش از ۲۰۰"),
                            ("unknown", "نمی\u200cدانم"),
                        ],
                        max_length=24,
                    ),
                ),
                ("sitemap_url", models.URLField(blank=True, max_length=1000)),
                ("operator_note", models.TextField(blank=True, max_length=5000)),
                ("authority_declared", models.BooleanField(default=False)),
                ("preview", models.JSONField(blank=True, default=dict)),
                (
                    "discovery_stage",
                    models.CharField(
                        choices=[
                            ("awaiting_url", "در انتظار تأیید نشانی"),
                            ("queued", "در انتظار کشف"),
                            ("running", "در حال کشف"),
                            ("complete", "کشف پایان یافت؛ در انتظار بررسی پروفایل"),
                            ("failed", "کشف ناموفق"),
                            ("released", "رزرو آزاد شده"),
                        ],
                        default="awaiting_url",
                        max_length=24,
                    ),
                ),
                ("preview_confirmed", models.BooleanField(default=False)),
                ("needs_reconciliation", models.BooleanField(default=False, editable=False)),
                ("pending_since", models.DateTimeField(blank=True, editable=False, null=True)),
                ("discarded_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "responsible_operator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responsible_source_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="source_proposals",
                        to="catalog.source",
                    ),
                ),
                (
                    "submitter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at",),
                "permissions": (("review_source_proposal", "Can review Source Proposals"),),
            },
        ),
        migrations.CreateModel(
            name="SourceCaseResponsibilityChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("revision", models.PositiveIntegerField()),
                ("reason", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=apps.common.deletion.set_null_in_immutable_history,
                        related_name="source_case_responsibility_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        null=True,
                        on_delete=apps.common.deletion.set_null_in_immutable_history,
                        related_name="source_case_responsibilities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="responsibility_history",
                        to="source_proposals.sourceproposal",
                    ),
                ),
            ],
            options={
                "ordering": ("revision",),
            },
        ),
        migrations.AddField(
            model_name="sourceassignment",
            name="proposal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="source_proposals.sourceproposal"
            ),
        ),
        migrations.AddField(
            model_name="externallistingcandidate",
            name="source_proposal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="external_listing_candidates",
                to="source_proposals.sourceproposal",
            ),
        ),
        migrations.CreateModel(
            name="SourceProposalEvent",
            fields=[
                (
                    "processing_action",
                    models.CharField(blank=True, db_default="", default="", max_length=6),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("revision", models.PositiveIntegerField()),
                (
                    "prior_state",
                    models.CharField(
                        choices=[
                            ("draft", "پیش\u200cنویس"),
                            ("pending", "در انتظار بررسی"),
                            ("changes_requested", "نیازمند اصلاح"),
                            ("rejected", "ردشده"),
                            ("approved", "تأییدشده"),
                            ("revoked", "تخصیص لغوشده"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "new_state",
                    models.CharField(
                        choices=[
                            ("draft", "پیش\u200cنویس"),
                            ("pending", "در انتظار بررسی"),
                            ("changes_requested", "نیازمند اصلاح"),
                            ("rejected", "ردشده"),
                            ("approved", "تأییدشده"),
                            ("revoked", "تخصیص لغوشده"),
                        ],
                        max_length=24,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=apps.common.deletion.set_null_in_immutable_history,
                        related_name="source_proposal_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="source_proposals.sourceproposal",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.AddField(
            model_name="sourceprofiledecision",
            name="event",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                to="source_proposals.sourceproposalevent",
            ),
        ),
        migrations.AddField(
            model_name="sourceassignment",
            name="revocation",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="revoked_assignment",
                to="source_proposals.sourceproposalevent",
            ),
        ),
        migrations.CreateModel(
            name="SourceProposalReviewClaim",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("revision", models.PositiveIntegerField()),
                ("expires_at", models.DateTimeField()),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="source_proposal_review_claims",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_claims",
                        to="source_proposals.sourceproposal",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="SourcePublicationModeChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("revision", models.PositiveIntegerField()),
                (
                    "review_mode",
                    models.CharField(
                        choices=[("approval_required", "نیازمند تأیید"), ("automatic", "خودکار")],
                        max_length=24,
                    ),
                ),
                (
                    "approval",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="publication_changes",
                        to="source_proposals.sourceprofiledecision",
                    ),
                ),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="publication_mode_change",
                        to="source_proposals.sourceproposalevent",
                    ),
                ),
            ],
            options={
                "ordering": ("revision",),
            },
        ),
        migrations.CreateModel(
            name="SourceReservation",
            fields=[
                ("discovery_checkpoint", models.JSONField(db_default={}, default=dict)),
                ("discovery_generation", models.PositiveIntegerField(db_default=0, default=0)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("revision", models.PositiveIntegerField()),
                ("approved_url", models.URLField(max_length=1000)),
                ("max_pages", models.PositiveIntegerField(default=50)),
                ("target_detail_pages", models.PositiveIntegerField(default=30)),
                ("expires_at", models.DateTimeField()),
                ("released_at", models.DateTimeField(null=True)),
                ("release_reason", models.CharField(blank=True, max_length=32)),
                ("started_at", models.DateTimeField(null=True)),
                ("completed_at", models.DateTimeField(null=True)),
                ("evidence", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="source_proposals.sourceproposal",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalog.source"
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="sourceprofileversion",
            name="reservation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="profile_versions",
                to="source_proposals.sourcereservation",
            ),
        ),
        migrations.CreateModel(
            name="SourceProfileSnapshots",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("pages", models.JSONField()),
                ("expires_at", models.DateTimeField()),
                (
                    "reservation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="source_proposals.sourcereservation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SourceResponsibilityChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("revision", models.PositiveIntegerField()),
                ("reason", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=apps.common.deletion.set_null_in_immutable_history,
                        related_name="source_responsibility_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        null=True,
                        on_delete=apps.common.deletion.set_null_in_immutable_history,
                        related_name="source_responsibilities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="responsibility_history",
                        to="catalog.source",
                    ),
                ),
            ],
            options={
                "ordering": ("revision",),
            },
        ),
        migrations.CreateModel(
            name="CandidateImageVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("kind", models.CharField(max_length=8)),
                ("width", models.PositiveIntegerField()),
                ("height", models.PositiveIntegerField()),
                ("byte_size", models.PositiveIntegerField()),
                (
                    "asset",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="candidate_variants",
                        to="common.mediaasset",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="variants",
                        to="source_proposals.candidateimage",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("image", "kind"), name="unique_candidate_image_variant"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="candidateimage",
            constraint=models.UniqueConstraint(
                fields=("candidate", "source_order"), name="unique_candidate_image_source_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="candidateimage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("candidate",),
                name="one_primary_candidate_image",
            ),
        ),
        migrations.AddConstraint(
            model_name="externallistingcandidatereviewclaim",
            constraint=models.UniqueConstraint(
                condition=models.Q(("released_at__isnull", True)),
                fields=("candidate", "revision"),
                name="one_open_external_candidate_claim_per_revision",
            ),
        ),
        migrations.AddConstraint(
            model_name="extractionrundecision",
            constraint=models.UniqueConstraint(
                fields=("run", "revision"), name="one_decision_per_run_revision"
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceexceptionnotice",
            constraint=models.UniqueConstraint(
                fields=("source", "summary_date"), name="one_source_exception_summary_daily"
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceexclusionaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("action", "remove")),
                fields=("exclusion",),
                name="one_exclusion_removal",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceextractionexception",
            constraint=models.UniqueConstraint(
                fields=("source", "canonical_url"), name="unique_source_exception_url"
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceexceptionattempt",
            constraint=models.UniqueConstraint(
                fields=("exception", "run", "attempt"), name="unique_exception_run_attempt"
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceimagehost",
            constraint=models.UniqueConstraint(
                fields=("source", "host"), name="unique_source_image_host"
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceproposal",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("discarded_at__isnull", True),
                    ("state__in", ("draft", "pending", "changes_requested")),
                    models.Q(("normalized_domain", ""), _negated=True),
                ),
                fields=("submitter", "normalized_domain"),
                name="one_open_source_proposal_per_account_domain",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcecaseresponsibilitychange",
            constraint=models.UniqueConstraint(
                fields=("proposal", "revision"), name="unique_source_case_responsibility_revision"
            ),
        ),
        migrations.AddConstraint(
            model_name="externallistingcandidate",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("discovery_version__isnull", True), ("extraction_run__isnull", True)
                ),
                fields=("source_proposal", "external_url"),
                name="unique_external_candidate_url_per_proposal",
            ),
        ),
        migrations.AddConstraint(
            model_name="externallistingcandidate",
            constraint=models.UniqueConstraint(
                fields=("extraction_run", "external_url"), name="unique_candidate_url_per_run"
            ),
        ),
        migrations.AddConstraint(
            model_name="externallistingcandidate",
            constraint=models.UniqueConstraint(
                fields=("discovery_version", "external_url"), name="unique_discovery_candidate_url"
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("revoked_at__isnull", True)),
                fields=("source",),
                name="one_active_assignment_per_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceproposalreviewclaim",
            constraint=models.UniqueConstraint(
                condition=models.Q(("released_at__isnull", True)),
                fields=("proposal", "revision"),
                name="one_open_source_proposal_claim_per_revision",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcepublicationmodechange",
            constraint=models.UniqueConstraint(
                fields=("approval", "revision"), name="unique_publication_mode_revision"
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcereservation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("released_at__isnull", True)),
                fields=("source",),
                name="one_open_reservation_per_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceprofileversion",
            constraint=models.UniqueConstraint(
                fields=("profile", "number"), name="unique_source_profile_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceprofileversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("provenance", "discovery")),
                fields=("reservation",),
                name="one_initial_profile_per_discovery",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceresponsibilitychange",
            constraint=models.UniqueConstraint(
                fields=("source", "revision"), name="unique_source_responsibility_revision"
            ),
        ),
    ]
