# Generated by Django 6.1 on 2026-08-31 09:04
# ruff: noqa: E501

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceProposal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("draft", "پیش\u200cنویس"), ("pending", "در انتظار بررسی")],
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "current_step",
                    models.CharField(
                        choices=[
                            ("details", "اطلاعات وب\u200cسایت"),
                            ("preview", "پیش\u200cنمایش شبیه\u200cسازی\u200cشده"),
                        ],
                        default="details",
                        max_length=16,
                    ),
                ),
                ("website_name", models.CharField(blank=True, max_length=200)),
                ("website_url", models.URLField(blank=True, max_length=1000)),
                ("normalized_domain", models.CharField(blank=True, db_index=True, max_length=253)),
                (
                    "relationship",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("website_owner", "مالک وب\u200cسایت"),
                            ("website_manager", "مدیر وب\u200cسایت"),
                            ("authorized_representative", "نماینده مجاز"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "inventory_range",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1_10", "۱ تا ۱۰"),
                            ("11_50", "۱۱ تا ۵۰"),
                            ("51_200", "۵۱ تا ۲۰۰"),
                            ("more_than_200", "بیش از ۲۰۰"),
                            ("unknown", "نمی\u200cدانم"),
                        ],
                        max_length=24,
                    ),
                ),
                ("sitemap_url", models.URLField(blank=True, max_length=1000)),
                ("operator_note", models.TextField(blank=True, max_length=5000)),
                ("authority_declared", models.BooleanField(default=False)),
                ("preview", models.JSONField(blank=True, default=dict)),
                ("preview_confirmed", models.BooleanField(default=False)),
                ("needs_reconciliation", models.BooleanField(default=False, editable=False)),
                ("pending_since", models.DateTimeField(blank=True, editable=False, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "submitter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at",),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("state__in", ("draft", "pending")),
                            models.Q(("normalized_domain", ""), _negated=True),
                        ),
                        fields=("submitter", "normalized_domain"),
                        name="one_open_source_proposal_per_account_domain",
                    )
                ],
            },
        ),
    ]
