# Generated by Django 6.1 on 2026-09-01 05:25

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0012_propertyimage_propertyimagevariant"),
        ("source_proposals", "0002_review_capability"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceProposalEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("revision", models.PositiveIntegerField()),
                (
                    "prior_state",
                    models.CharField(
                        choices=[
                            ("draft", "پیش\u200cنویس"),
                            ("pending", "در انتظار بررسی"),
                            ("changes_requested", "نیازمند اصلاح"),
                            ("rejected", "ردشده"),
                            ("approved", "تأییدشده"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "new_state",
                    models.CharField(
                        choices=[
                            ("draft", "پیش\u200cنویس"),
                            ("pending", "در انتظار بررسی"),
                            ("changes_requested", "نیازمند اصلاح"),
                            ("rejected", "ردشده"),
                            ("approved", "تأییدشده"),
                        ],
                        max_length=24,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="SourceProposalReviewClaim",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("revision", models.PositiveIntegerField()),
                ("expires_at", models.DateTimeField()),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.RemoveConstraint(
            model_name="sourceproposal",
            name="one_open_source_proposal_per_account_domain",
        ),
        migrations.AddField(
            model_name="sourceproposal",
            name="revision",
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name="sourceproposal",
            name="source",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="source_proposals",
                to="catalog.source",
            ),
        ),
        migrations.AlterField(
            model_name="sourceproposal",
            name="state",
            field=models.CharField(
                choices=[
                    ("draft", "پیش\u200cنویس"),
                    ("pending", "در انتظار بررسی"),
                    ("changes_requested", "نیازمند اصلاح"),
                    ("rejected", "ردشده"),
                    ("approved", "تأییدشده"),
                ],
                default="draft",
                max_length=24,
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceproposal",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("state__in", ("draft", "pending", "changes_requested")),
                    models.Q(("normalized_domain", ""), _negated=True),
                ),
                fields=("submitter", "normalized_domain"),
                name="one_open_source_proposal_per_account_domain",
            ),
        ),
        migrations.AddField(
            model_name="sourceproposalevent",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="source_proposal_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sourceproposalevent",
            name="proposal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="source_proposals.sourceproposal",
            ),
        ),
        migrations.AddField(
            model_name="sourceproposalreviewclaim",
            name="operator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="source_proposal_review_claims",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sourceproposalreviewclaim",
            name="proposal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_claims",
                to="source_proposals.sourceproposal",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceproposalreviewclaim",
            constraint=models.UniqueConstraint(
                condition=models.Q(("released_at__isnull", True)),
                fields=("proposal", "revision"),
                name="one_open_source_proposal_claim_per_revision",
            ),
        ),
    ]
