# Generated by Django 6.1 on 2026-09-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("source_proposals", "0002_listing_publication_authority"),
    ]

    operations = [
        migrations.AddField(
            model_name="extractionrequest",
            name="max_pages",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="extractionrequest",
            name="target_detail_pages",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="extractionrun",
            name="progress_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="extractionrun",
            name="stage",
            field=models.CharField(
                choices=[
                    ("discovering", "کشف صفحات"),
                    ("extracting", "استخراج اطلاعات"),
                    ("preparing", "آماده\u200cسازی نتایج"),
                ],
                db_default="discovering",
                default="discovering",
                max_length=24,
            ),
        ),
    ]
