# Generated by Django 6.1 on 2026-09-01 06:03

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0012_propertyimage_propertyimagevariant"),
        ("source_proposals", "0003_sourceproposalevent_sourceproposalreviewclaim_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalListingCandidate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار بررسی"),
                            ("changes_requested", "نیازمند اصلاح"),
                            ("rejected", "ردشده"),
                            ("published", "منتشرشده"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("revision", models.PositiveIntegerField(default=1, editable=False)),
                ("simulated", models.BooleanField(default=True, editable=False)),
                ("title", models.CharField(max_length=200)),
                ("external_url", models.URLField(max_length=1000)),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("apartment", "آپارتمان"),
                            ("house", "خانه"),
                            ("villa", "ویلا"),
                            ("office", "دفتر اداری"),
                            ("shop", "مغازه"),
                            ("warehouse", "انبار"),
                            ("workshop", "کارگاه"),
                        ],
                        max_length=16,
                    ),
                ),
                ("area_sqm", models.PositiveIntegerField()),
                ("room_count", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("deposit_rial", models.PositiveBigIntegerField()),
                ("monthly_rent_rial", models.PositiveBigIntegerField()),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalog.city"
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalog.district"
                    ),
                ),
                (
                    "listing",
                    models.OneToOneField(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="external_candidate",
                        to="catalog.listing",
                    ),
                ),
                (
                    "neighborhood",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalog.neighborhood"
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="external_listing_candidates",
                        to="catalog.source",
                    ),
                ),
                (
                    "source_proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="external_listing_candidates",
                        to="source_proposals.sourceproposal",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source_proposal", "external_url"),
                        name="unique_external_candidate_url_per_proposal",
                    )
                ],
            },
        ),
    ]
