# Generated by Django 6.1 on 2026-09-03 09:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0013_reduce_approximate_location_radius"),
        ("source_proposals", "0005_externallistingcandidateevent_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="sourceproposal",
            name="one_open_source_proposal_per_account_domain",
        ),
        migrations.AddField(
            model_name="sourceproposal",
            name="discarded_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name="sourceproposal",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("discarded_at__isnull", True),
                    ("state__in", ("draft", "pending", "changes_requested")),
                    models.Q(("normalized_domain", ""), _negated=True),
                ),
                fields=("submitter", "normalized_domain"),
                name="one_open_source_proposal_per_account_domain",
            ),
        ),
    ]
