# Generated by Django 6.1 on 2026-09-04 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.common.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "source_proposals",
            "0006_remove_sourceproposal_one_open_source_proposal_per_account_domain_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="sourceproposal",
            name="submitter",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_proposals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="sourceproposalevent",
            name="actor",
            field=models.ForeignKey(
                null=True,
                on_delete=apps.common.deletion.set_null_in_immutable_history,
                related_name="source_proposal_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
