# Generated by Django 6.1 on 2026-09-05 06:27

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0014_reference_common_media_asset"),
        ("source_proposals", "0007_preserve_history_after_submitter_deletion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sourceproposal",
            name="discovery_stage",
            field=models.CharField(
                choices=[
                    ("awaiting_url", "در انتظار تأیید نشانی"),
                    ("queued", "در انتظار کشف"),
                    ("running", "در حال کشف"),
                    ("complete", "کشف پایان یافت؛ در انتظار بررسی پروفایل"),
                    ("failed", "کشف ناموفق"),
                    ("released", "رزرو آزاد شده"),
                ],
                default="awaiting_url",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="sourceproposal",
            name="current_step",
            field=models.CharField(
                choices=[("details", "اطلاعات وب\u200cسایت"), ("preview", "بازبینی اطلاعات")],
                default="details",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="SourceAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("revoked_at", models.DateTimeField(null=True)),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="source_proposals.sourceproposal",
                    ),
                ),
                (
                    "representative",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="catalog.source",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("revoked_at__isnull", True)),
                        fields=("source",),
                        name="one_active_assignment_per_source",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SourceReservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("revision", models.PositiveIntegerField()),
                ("approved_url", models.URLField(max_length=1000)),
                ("expires_at", models.DateTimeField()),
                ("released_at", models.DateTimeField(null=True)),
                ("release_reason", models.CharField(blank=True, max_length=32)),
                ("started_at", models.DateTimeField(null=True)),
                ("completed_at", models.DateTimeField(null=True)),
                ("evidence", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="source_proposals.sourceproposal",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalog.source"
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("released_at__isnull", True)),
                        fields=("source",),
                        name="one_open_reservation_per_source",
                    )
                ],
            },
        ),
    ]
