# Generated by Django 6.1 on 2026-09-05 06:54

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.common.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0014_reference_common_media_asset"),
        ("source_proposals", "0008_sourceproposal_discovery_stage_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "source",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="profile",
                        to="catalog.source",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SourceProfileSnapshots",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("pages", models.JSONField()),
                ("expires_at", models.DateTimeField()),
                (
                    "reservation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="source_proposals.sourcereservation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SourceProfileVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("rules", models.JSONField()),
                ("structural_fingerprint", models.TextField()),
                ("validation", models.JSONField()),
                ("samples", models.JSONField()),
                ("exclusions", models.JSONField()),
                ("diagnostics", models.JSONField(default=dict)),
                ("pipeline_version", models.CharField(max_length=64)),
                (
                    "provenance",
                    models.CharField(
                        choices=[("discovery", "Discovery"), ("manual", "Manual")], max_length=16
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=apps.common.deletion.set_null_in_immutable_history,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="source_proposals.sourceprofileversion",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="source_proposals.sourceprofile",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="profile_versions",
                        to="source_proposals.sourcereservation",
                    ),
                ),
            ],
            options={
                "ordering": ("-number",),
            },
        ),
        migrations.CreateModel(
            name="SourceProfileDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "review_mode",
                    models.CharField(
                        blank=True,
                        choices=[("approval_required", "نیازمند تأیید"), ("automatic", "خودکار")],
                        max_length=24,
                    ),
                ),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="source_proposals.sourceproposalevent",
                    ),
                ),
                (
                    "version",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decision",
                        to="source_proposals.sourceprofileversion",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="sourceprofile",
            name="active_version",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="active_profile",
                to="source_proposals.sourceprofileversion",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceprofileversion",
            constraint=models.UniqueConstraint(
                fields=("profile", "number"), name="unique_source_profile_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceprofileversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("provenance", "discovery")),
                fields=("reservation",),
                name="one_initial_profile_per_discovery",
            ),
        ),
    ]
