# Generated by Django 6.1 on 2026-09-05 07:27

import django.db.models.deletion
from django.apps.registry import Apps
from django.conf import settings
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor

import apps.common.deletion


def link_recorded_approvals(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    database = schema_editor.connection.alias
    Decision = apps.get_model("source_proposals", "SourceProfileDecision")
    Assignment = apps.get_model("source_proposals", "SourceAssignment")
    for decision in Decision.objects.using(database).select_related(
        "event__proposal", "version__reservation"
    ):
        representative_id = decision.event.proposal.submitter_id
        Decision.objects.using(database).filter(pk=decision.pk).update(
            representative_id=representative_id
        )
        if decision.event.new_state != "approved":
            continue
        matches = Assignment.objects.using(database).filter(
            proposal_id=decision.event.proposal_id,
            source_id=decision.version.reservation.source_id,
            representative_id=representative_id,
        )
        # Only link an unambiguous recorded approval; legacy authorization stays unknown.
        if matches.count() == 1:
            matches.filter(approval__isnull=True).update(approval_id=decision.pk)


class Migration(migrations.Migration):
    dependencies = [
        ("source_proposals", "0009_sourceprofile_sourceprofilesnapshots_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sourceassignment",
            name="approval",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assignment",
                to="source_proposals.sourceprofiledecision",
            ),
        ),
        migrations.AddField(
            model_name="sourceprofiledecision",
            name="representative",
            field=models.ForeignKey(
                null=True,
                on_delete=apps.common.deletion.set_null_in_immutable_history,
                related_name="source_profile_decisions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(link_recorded_approvals, migrations.RunPython.noop),
    ]
