# Generated by Django 6.1 on 2026-09-05 08:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import apps.common.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("source_proposals", "0010_sourceassignment_approval_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="sourceprofileversion",
            name="provenance",
            field=models.CharField(
                choices=[("discovery", "Discovery"), ("manual", "Manual"), ("llm", "LLM repair")],
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="SourceProfileRepair",
            fields=[
                ("id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("reviewed_revision", models.PositiveIntegerField()),
                ("selected_fields", models.JSONField()),
                ("model", models.CharField(max_length=128)),
                ("prompt_version", models.CharField(max_length=64)),
                ("schema_version", models.CharField(max_length=64)),
                ("evidence_sha256", models.CharField(max_length=64)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=apps.common.deletion.set_null_in_immutable_history,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="repairs",
                        to="source_proposals.sourceprofileversion",
                    ),
                ),
            ],
            options={
                "ordering": ("-started_at",),
            },
        ),
        migrations.CreateModel(
            name="SourceProfileRepairResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("outcome", models.CharField(max_length=32)),
                ("detail", models.TextField()),
                ("structured_result", models.JSONField(null=True)),
                ("validation", models.JSONField(default=dict)),
                ("finished_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("duration_ms", models.PositiveIntegerField()),
                (
                    "repair",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="result",
                        to="source_proposals.sourceprofilerepair",
                    ),
                ),
                (
                    "result_version",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="source_proposals.sourceprofileversion",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
