# Generated by Django 6.1 on 2026-09-05 08:01

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("source_proposals", "0010_sourceassignment_approval_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtractionRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("submitted_url", models.URLField(max_length=1000)),
                ("canonical_url", models.URLField(max_length=1000)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("queued", "در صف"),
                            ("running", "در حال استخراج"),
                            ("complete", "پایان یافته"),
                            ("failed", "ناموفق"),
                            ("cancelled", "لغوشده"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requests",
                        to="source_proposals.sourceassignment",
                    ),
                ),
                (
                    "profile_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="source_proposals.sourceprofileversion",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="ExtractionRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("pipeline_version", models.CharField(max_length=64)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("queued", "در صف"),
                            ("running", "در حال استخراج"),
                            ("complete", "پایان یافته"),
                            ("failed", "ناموفق"),
                            ("cancelled", "لغوشده"),
                        ],
                        default="running",
                        max_length=16,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=1)),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(null=True)),
                ("discovered", models.PositiveIntegerField(default=0)),
                ("extracted", models.PositiveIntegerField(default=0)),
                ("published", models.PositiveIntegerField(default=0)),
                ("needs_attention", models.PositiveIntegerField(default=0)),
                ("rejected", models.PositiveIntegerField(default=0)),
                ("failed", models.PositiveIntegerField(default=0)),
                ("errors", models.JSONField(default=list)),
                ("results", models.JSONField(default=list)),
                (
                    "profile_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="source_proposals.sourceprofileversion",
                    ),
                ),
                (
                    "request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="run",
                        to="source_proposals.extractionrequest",
                    ),
                ),
            ],
        ),
    ]
