# Generated by Django 6.1 on 2026-09-05 08:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("source_proposals", "0011_alter_sourceprofileversion_provenance_and_more"),
        ("source_proposals", "0011_extractionrequest_extractionrun"),
    ]

    operations = []
