# Generated by Django 6.1 on 2026-09-05 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0014_reference_common_media_asset"),
        ("source_proposals", "0012_merge_20260905_0823"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtractionRunDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("revision", models.PositiveIntegerField()),
                ("candidate_ids", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="externallistingcandidate",
            name="unique_external_candidate_url_per_proposal",
        ),
        migrations.AddField(
            model_name="externallistingcandidate",
            name="conflicts",
            field=models.JSONField(db_default={}, default=dict),
        ),
        migrations.AddField(
            model_name="externallistingcandidate",
            name="corrections",
            field=models.JSONField(db_default={}, default=dict),
        ),
        migrations.AddField(
            model_name="externallistingcandidate",
            name="evidence",
            field=models.JSONField(db_default={}, default=dict),
        ),
        migrations.AddField(
            model_name="externallistingcandidate",
            name="extraction_run",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="candidates",
                to="source_proposals.extractionrun",
            ),
        ),
        migrations.AddField(
            model_name="externallistingcandidate",
            name="source_claims",
            field=models.JSONField(db_default={}, default=dict),
        ),
        migrations.AddField(
            model_name="externallistingcandidate",
            name="validation_errors",
            field=models.JSONField(db_default={}, default=dict),
        ),
        migrations.AddField(
            model_name="extractionrun",
            name="candidate_rejected",
            field=models.PositiveIntegerField(db_default=0, default=0),
        ),
        migrations.AddField(
            model_name="extractionrun",
            name="revision",
            field=models.PositiveIntegerField(db_default=1, default=1),
        ),
        migrations.AlterField(
            model_name="externallistingcandidate",
            name="area_sqm",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="externallistingcandidate",
            name="city",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="catalog.city"
            ),
        ),
        migrations.AlterField(
            model_name="externallistingcandidate",
            name="deposit_rial",
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="externallistingcandidate",
            name="district",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="catalog.district"
            ),
        ),
        migrations.AlterField(
            model_name="externallistingcandidate",
            name="listing",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="external_candidates",
                to="catalog.listing",
            ),
        ),
        migrations.AlterField(
            model_name="externallistingcandidate",
            name="monthly_rent_rial",
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="externallistingcandidate",
            name="neighborhood",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="catalog.neighborhood"
            ),
        ),
        migrations.AlterField(
            model_name="externallistingcandidate",
            name="property_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("apartment", "آپارتمان"),
                    ("house", "خانه"),
                    ("villa", "ویلا"),
                    ("office", "دفتر اداری"),
                    ("shop", "مغازه"),
                    ("warehouse", "انبار"),
                    ("workshop", "کارگاه"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="externallistingcandidate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("extraction_run__isnull", True)),
                fields=("source_proposal", "external_url"),
                name="unique_external_candidate_url_per_proposal",
            ),
        ),
        migrations.AddConstraint(
            model_name="externallistingcandidate",
            constraint=models.UniqueConstraint(
                fields=("extraction_run", "external_url"), name="unique_candidate_url_per_run"
            ),
        ),
        migrations.AddField(
            model_name="extractionrundecision",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="extractionrundecision",
            name="run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="decisions",
                to="source_proposals.extractionrun",
            ),
        ),
        migrations.AddConstraint(
            model_name="extractionrundecision",
            constraint=models.UniqueConstraint(
                fields=("run", "revision"), name="one_decision_per_run_revision"
            ),
        ),
    ]
