# Generated by Django 6.1 on 2026-09-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("source_proposals", "0013_extractionrundecision_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="externallistingcandidateevent",
            name="corrections",
            field=models.JSONField(db_default={}, default=dict),
        ),
        migrations.AddField(
            model_name="extractionrun",
            name="withdrawals",
            field=models.JSONField(db_default=[], default=list),
        ),
    ]
