# Generated by Django 6.1 on 2026-09-05 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("source_proposals", "0014_externallistingcandidateevent_corrections_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="externallistingcandidateevent",
            name="actor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="external_listing_candidate_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
