# Generated by Django 6.1 on 2026-09-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("source_proposals", "0015_alter_externallistingcandidateevent_actor"),
    ]

    # Unknown authority on legacy requests fails closed; submit a fresh request.
    # The database default lets older workers finish during a rolling deployment.
    operations = [
        migrations.AddField(
            model_name="extractionrequest",
            name="review_mode",
            field=models.CharField(
                choices=[("approval_required", "نیازمند تأیید"), ("automatic", "خودکار")],
                db_default="",
                default="",
                max_length=24,
            ),
        ),
    ]
