# Generated by Django 6.1 on 2026-09-05 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("source_proposals", "0016_extractionrequest_review_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourceassignment",
            name="revocation",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="revoked_assignment",
                to="source_proposals.sourceproposalevent",
            ),
        ),
        migrations.AlterField(
            model_name="externallistingcandidate",
            name="state",
            field=models.CharField(
                choices=[
                    ("pending", "در انتظار بررسی"),
                    ("changes_requested", "نیازمند اصلاح"),
                    ("rejected", "ردشده"),
                    ("published", "منتشرشده"),
                    ("cancelled", "لغوشده"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="externallistingcandidateevent",
            name="new_state",
            field=models.CharField(
                choices=[
                    ("pending", "در انتظار بررسی"),
                    ("changes_requested", "نیازمند اصلاح"),
                    ("rejected", "ردشده"),
                    ("published", "منتشرشده"),
                    ("cancelled", "لغوشده"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="externallistingcandidateevent",
            name="prior_state",
            field=models.CharField(
                choices=[
                    ("pending", "در انتظار بررسی"),
                    ("changes_requested", "نیازمند اصلاح"),
                    ("rejected", "ردشده"),
                    ("published", "منتشرشده"),
                    ("cancelled", "لغوشده"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="sourceproposal",
            name="state",
            field=models.CharField(
                choices=[
                    ("draft", "پیش\u200cنویس"),
                    ("pending", "در انتظار بررسی"),
                    ("changes_requested", "نیازمند اصلاح"),
                    ("rejected", "ردشده"),
                    ("approved", "تأییدشده"),
                    ("revoked", "تخصیص لغوشده"),
                ],
                default="draft",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="sourceproposalevent",
            name="new_state",
            field=models.CharField(
                choices=[
                    ("draft", "پیش\u200cنویس"),
                    ("pending", "در انتظار بررسی"),
                    ("changes_requested", "نیازمند اصلاح"),
                    ("rejected", "ردشده"),
                    ("approved", "تأییدشده"),
                    ("revoked", "تخصیص لغوشده"),
                ],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="sourceproposalevent",
            name="prior_state",
            field=models.CharField(
                choices=[
                    ("draft", "پیش\u200cنویس"),
                    ("pending", "در انتظار بررسی"),
                    ("changes_requested", "نیازمند اصلاح"),
                    ("rejected", "ردشده"),
                    ("approved", "تأییدشده"),
                    ("revoked", "تخصیص لغوشده"),
                ],
                max_length=24,
            ),
        ),
    ]
