# Generated by Django 6.1 on 2026-09-05 10:09

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0014_reference_common_media_asset"),
        ("common", "0001_move_media_asset_state"),
        ("source_proposals", "0017_sourceassignment_revocation_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CandidateImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("original_url", models.URLField(max_length=2000)),
                ("source_order", models.PositiveSmallIntegerField()),
                ("position", models.PositiveSmallIntegerField()),
                ("is_primary", models.BooleanField(default=False)),
                ("excluded", models.BooleanField(default=False)),
                ("state", models.CharField(default="pending", max_length=16)),
                ("failure_code", models.CharField(blank=True, max_length=64)),
                ("content_hash", models.CharField(blank=True, max_length=64)),
                ("accepted_at", models.DateTimeField(null=True)),
                ("unreferenced_at", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "accepted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accepted_external_images",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="images",
                        to="source_proposals.externallistingcandidate",
                    ),
                ),
                (
                    "listing_image",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="external_origin",
                        to="catalog.listingimage",
                    ),
                ),
                (
                    "property_image",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="external_origins",
                        to="catalog.propertyimage",
                    ),
                ),
            ],
            options={
                "ordering": ("position", "source_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="CandidateImageVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("kind", models.CharField(max_length=8)),
                ("width", models.PositiveIntegerField()),
                ("height", models.PositiveIntegerField()),
                ("byte_size", models.PositiveIntegerField()),
                (
                    "asset",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="candidate_variants",
                        to="common.mediaasset",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="variants",
                        to="source_proposals.candidateimage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SourceImageHost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("host", models.CharField(max_length=253)),
                ("approved_at", models.DateTimeField(auto_now_add=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="image_hosts",
                        to="catalog.source",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="candidateimage",
            constraint=models.UniqueConstraint(
                fields=("candidate", "source_order"), name="unique_candidate_image_source_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="candidateimage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("candidate",),
                name="one_primary_candidate_image",
            ),
        ),
        migrations.AddConstraint(
            model_name="candidateimagevariant",
            constraint=models.UniqueConstraint(
                fields=("image", "kind"), name="unique_candidate_image_variant"
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceimagehost",
            constraint=models.UniqueConstraint(
                fields=("source", "host"), name="unique_source_image_host"
            ),
        ),
    ]
