# Generated by Django 6.1 on 2026-09-05 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("source_proposals", "0018_candidateimage_candidateimagevariant_sourceimagehost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="externallistingcandidate",
            name="discovery_version",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="media_candidates",
                to="source_proposals.sourceprofileversion",
            ),
        ),
    ]
