# Generated by Django 6.1 on 2026-09-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0014_reference_common_media_asset"),
        ("source_proposals", "0019_externallistingcandidate_discovery_version"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="externallistingcandidate",
            name="unique_external_candidate_url_per_proposal",
        ),
        migrations.AddConstraint(
            model_name="externallistingcandidate",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("discovery_version__isnull", True), ("extraction_run__isnull", True)
                ),
                fields=("source_proposal", "external_url"),
                name="unique_external_candidate_url_per_proposal",
            ),
        ),
        migrations.AddConstraint(
            model_name="externallistingcandidate",
            constraint=models.UniqueConstraint(
                fields=("discovery_version", "external_url"), name="unique_discovery_candidate_url"
            ),
        ),
    ]
