# Generated by Django 6.1 on 2026-09-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "source_proposals",
            "0020_remove_externallistingcandidate_unique_external_candidate_url_per_proposal_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidateimage",
            name="original_url",
            field=models.TextField(),
        ),
    ]
