# Generated by Django 6.1 on 2026-09-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("source_proposals", "0022_retire_simulation"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateimage",
            name="retention_checked_at",
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
