# Generated by Django 6.1 on 2026-09-06 06:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("source_proposals", "0023_candidateimage_retention_checked_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourcereservation",
            name="max_pages",
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name="sourcereservation",
            name="target_detail_pages",
            field=models.PositiveIntegerField(default=30),
        ),
    ]
