# Generated by Django 6.1 on 2026-09-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("source_proposals", "0024_sourcereservation_max_pages_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourceprofiledecision",
            name="limitations_acknowledged",
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
