# Generated by Django 6.1 on 2026-09-06 10:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import apps.common.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0015_source_responsibility_revision_and_more"),
        ("source_proposals", "0025_sourceprofiledecision_limitations_acknowledged"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceResponsibilityChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("revision", models.PositiveIntegerField()),
                ("reason", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=apps.common.deletion.set_null_in_immutable_history,
                        related_name="source_responsibility_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        null=True,
                        on_delete=apps.common.deletion.set_null_in_immutable_history,
                        related_name="source_responsibilities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="responsibility_history",
                        to="catalog.source",
                    ),
                ),
            ],
            options={
                "ordering": ("revision",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "revision"), name="unique_source_responsibility_revision"
                    )
                ],
            },
        ),
    ]
