# Generated by Django 6.1 on 2026-09-06 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("source_proposals", "0027_initialize_source_responsibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="extractionrequest",
            name="publication_revision",
            field=models.PositiveIntegerField(db_default=0, default=0),
        ),
        migrations.CreateModel(
            name="SourcePublicationModeChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("revision", models.PositiveIntegerField()),
                (
                    "review_mode",
                    models.CharField(
                        choices=[("approval_required", "نیازمند تأیید"), ("automatic", "خودکار")],
                        max_length=24,
                    ),
                ),
                (
                    "approval",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="publication_changes",
                        to="source_proposals.sourceprofiledecision",
                    ),
                ),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="publication_mode_change",
                        to="source_proposals.sourceproposalevent",
                    ),
                ),
            ],
            options={
                "ordering": ("revision",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("approval", "revision"), name="unique_publication_mode_revision"
                    )
                ],
            },
        ),
    ]
