# Generated by Django 6.1 on 2026-09-06 11:06

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.common.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0015_source_responsibility_revision_and_more"),
        ("source_proposals", "0028_extractionrequest_publication_revision_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceExclusion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("exact", "Exact URL"), ("path_prefix", "Path section")],
                        max_length=16,
                    ),
                ),
                ("url", models.URLField(max_length=1000)),
                ("reason", models.CharField(max_length=2000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=apps.common.deletion.set_null_in_immutable_history,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exclusions",
                        to="catalog.source",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.AddField(
            model_name="externallistingcandidate",
            name="exclusion_hold",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="held_candidates",
                to="source_proposals.sourceexclusion",
            ),
        ),
        migrations.CreateModel(
            name="SourceExclusionAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("remove", "Remove"), ("withdraw", "Withdraw Listings")],
                        max_length=16,
                    ),
                ),
                ("reason", models.CharField(max_length=2000)),
                ("listing_ids", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=apps.common.deletion.set_null_in_immutable_history,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exclusion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="actions",
                        to="source_proposals.sourceexclusion",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("action", "remove")),
                        fields=("exclusion",),
                        name="one_exclusion_removal",
                    )
                ],
            },
        ),
    ]
