# Generated by Django 6.1 on 2026-09-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("source_proposals", "0029_sourceexclusion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="extractionrun",
            name="skipped_pages",
            field=models.JSONField(db_default=[], default=list),
        ),
    ]
