# Generated by Django 6.1 on 2026-09-06 11:36

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0015_source_responsibility_revision_and_more"),
        ("source_proposals", "0030_extractionrun_skipped_pages"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceExtractionException",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("canonical_url", models.URLField(max_length=1000)),
                ("first_occurrence", models.DateTimeField(null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("open", "باز"),
                            ("resolved", "رفع شده"),
                            ("excluded", "کنار گذاشته شده"),
                        ],
                        max_length=16,
                    ),
                ),
                ("problem", models.CharField(blank=True, max_length=64)),
                ("detail", models.TextField(blank=True)),
                ("last_attempt", models.PositiveIntegerField()),
                ("last_attempt_at", models.DateTimeField()),
                (
                    "last_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="source_proposals.extractionrun",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exceptions",
                        to="catalog.source",
                    ),
                ),
            ],
            options={
                "ordering": ("canonical_url",),
            },
        ),
        migrations.CreateModel(
            name="SourceExceptionAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("attempt", models.PositiveIntegerField()),
                ("attempted_at", models.DateTimeField()),
                ("state", models.CharField(max_length=16)),
                ("problem", models.CharField(blank=True, max_length=64)),
                ("detail", models.TextField(blank=True)),
                ("is_current", models.BooleanField()),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="source_proposals.extractionrun",
                    ),
                ),
                (
                    "exception",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="source_proposals.sourceextractionexception",
                    ),
                ),
            ],
            options={
                "ordering": ("-attempted_at", "-id"),
            },
        ),
        migrations.AddConstraint(
            model_name="sourceextractionexception",
            constraint=models.UniqueConstraint(
                fields=("source", "canonical_url"), name="unique_source_exception_url"
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceexceptionattempt",
            constraint=models.UniqueConstraint(
                fields=("exception", "run", "attempt"), name="unique_exception_run_attempt"
            ),
        ),
    ]
