# Generated by Django 6.1 on 2026-09-06 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("source_proposals", "0031_sourceextractionexception_sourceexceptionattempt_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="extractionrequest",
            name="initiated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="initiated_extractions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
