# Generated by Django 6.1 on 2026-09-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("source_proposals", "0032_extractionrequest_initiated_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="extractionrequest",
            name="processing_revision",
            field=models.PositiveIntegerField(db_default=0, default=0),
        ),
    ]
