# Generated by Django 6.1 on 2026-09-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("source_proposals", "0033_extractionrequest_processing_revision"),
    ]

    operations = [
        migrations.AddField(
            model_name="externallistingcandidate",
            name="superseded",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name="sourceproposalevent",
            name="processing_action",
            field=models.CharField(blank=True, db_default="", default="", max_length=6),
        ),
    ]
