# Generated by Django 6.1 on 2026-09-06 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0016_source_processing_paused_source_processing_revision"),
        ("source_proposals", "0035_sourcebulkaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceExceptionNotificationState",
            fields=[
                (
                    "source",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="catalog.source",
                    ),
                ),
                ("pending_changes", models.JSONField(default=dict)),
                ("last_summary_date", models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SourceExceptionNotice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("summary", "Summary"), ("failure", "Failure")], max_length=16
                    ),
                ),
                ("changes", models.JSONField(default=dict)),
                ("summary_date", models.DateField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalog.source"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "summary_date"), name="one_source_exception_summary_daily"
                    )
                ],
            },
        ),
    ]
