# Generated by Django 6.1 on 2026-09-06 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("source_proposals", "0036_sourceexceptionnotificationstate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="extractionrun",
            name="attempted_pages",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="extractionrun",
            name="usable_results",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="sourceexceptionnotificationstate",
            name="failing",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sourceexceptionnotificationstate",
            name="failure_notified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sourceexceptionnotificationstate",
            name="last_attempt",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="sourceexceptionnotificationstate",
            name="last_run",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="source_proposals.extractionrun",
            ),
        ),
    ]
