# Generated by Django 6.1 on 2026-09-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("source_proposals", "0037_extractionrun_attempted_pages_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourceexceptionnotificationstate",
            name="last_delivery_check",
            field=models.DateTimeField(null=True),
        ),
    ]
