# Generated by Django 6.1 on 2026-09-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("source_proposals", "0039_restore_simulated_compatibility_column"),
    ]

    operations = [
        migrations.AddField(
            model_name="extractionrun",
            name="discovery_checkpoint",
            field=models.JSONField(db_default={}, default=dict),
        ),
        migrations.AddField(
            model_name="extractionrun",
            name="discovery_generation",
            field=models.PositiveIntegerField(db_default=0, default=0),
        ),
        migrations.AddField(
            model_name="extractionrun",
            name="discovery_stop_reason",
            field=models.CharField(db_default="", default="", max_length=32),
        ),
        migrations.AddField(
            model_name="sourcereservation",
            name="discovery_checkpoint",
            field=models.JSONField(db_default={}, default=dict),
        ),
        migrations.AddField(
            model_name="sourcereservation",
            name="discovery_generation",
            field=models.PositiveIntegerField(db_default=0, default=0),
        ),
    ]
