# Generated by Django 6.1 on 2026-09-12 07:22

from django.db import migrations, models


def recover_initial_deliveries(apps, schema_editor):
    requests = apps.get_model("source_proposals", "ExtractionRequest")
    requests.objects.using(schema_editor.connection.alias).filter(
        state="queued", run__isnull=True
    ).update(delivery_pending=True)


class Migration(migrations.Migration):
    dependencies = [
        ("source_proposals", "0040_extractionrun_discovery_checkpoint_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="extractionrequest",
            name="delivery_attempted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="extractionrequest",
            name="delivery_error",
            field=models.TextField(blank=True, db_default="", default=""),
        ),
        migrations.AddField(
            model_name="extractionrequest",
            name="delivery_pending",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.RunPython(recover_initial_deliveries, migrations.RunPython.noop),
    ]
