# Generated by Django 6.1 on 2026-09-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("source_proposals", "0041_extractionrequest_delivery_attempted_at_and_more"),
    ]

    operations = [
        # 0022 retained this physical column for old workers. Include it in temporary
        # migration state so SQLite table rebuilds preserve it in both directions.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="externallistingcandidate",
                    name="simulated",
                    field=models.BooleanField(default=False, db_default=False, editable=False),
                ),
            ],
        ),
        migrations.AddField(
            model_name="externallistingcandidate",
            name="publication_outcome",
            field=models.CharField(
                blank=True,
                choices=[
                    ("new", "آگهی جدید"),
                    ("updated", "به\u200cروزرسانی\u200cشده"),
                    ("unchanged", "بدون تغییر"),
                ],
                db_default="",
                default="",
                max_length=16,
            ),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(model_name="externallistingcandidate", name="simulated"),
            ],
        ),
    ]
