# Generated by Django 6.1 on 2026-09-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("source_proposals", "0042_externallistingcandidate_publication_outcome"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateimage",
            name="normalized_pixel_sha256",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="candidateimage",
            name="perceptual_dhash",
            field=models.CharField(blank=True, db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name="candidateimage",
            name="content_hash",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
