# Generated by Django 6.1 on 2026-09-17 10:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import apps.common.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("source_proposals", "0043_candidateimage_normalized_pixel_sha256_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sourceproposal",
            name="responsibility_revision",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="sourceproposal",
            name="responsible_operator",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="responsible_source_cases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="SourceCaseResponsibilityChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("revision", models.PositiveIntegerField()),
                ("reason", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=apps.common.deletion.set_null_in_immutable_history,
                        related_name="source_case_responsibility_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        null=True,
                        on_delete=apps.common.deletion.set_null_in_immutable_history,
                        related_name="source_case_responsibilities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="responsibility_history",
                        to="source_proposals.sourceproposal",
                    ),
                ),
            ],
            options={
                "ordering": ("revision",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("proposal", "revision"),
                        name="unique_source_case_responsibility_revision",
                    )
                ],
            },
        ),
    ]
