# Generated by Django 6.1 on 2026-09-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("source_proposals", "0045_backfill_case_responsibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="externallistingcandidate",
            name="requested_urls",
            field=models.JSONField(db_default=[], default=list),
        ),
        migrations.AddField(
            model_name="externallistingcandidate",
            name="structural_drift",
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
