# Generated by Django 6.1 on 2026-08-21 16:56

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name_fa", models.CharField(max_length=120)),
                ("source_code", models.CharField(max_length=64)),
                ("source_year", models.PositiveSmallIntegerField()),
                ("provenance_url", models.URLField(max_length=500)),
                ("imported_at", models.DateField()),
                ("reviewed", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "cities",
            },
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name_fa", models.CharField(max_length=120)),
                ("source_code", models.CharField(max_length=64)),
                ("source_year", models.PositiveSmallIntegerField()),
                ("provenance_url", models.URLField(max_length=500)),
                ("imported_at", models.DateField()),
                ("reviewed", models.BooleanField(default=False)),
                ("number", models.PositiveSmallIntegerField()),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="districts",
                        to="catalog.city",
                    ),
                ),
            ],
            options={
                "ordering": ("number",),
            },
        ),
        migrations.CreateModel(
            name="Neighborhood",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name_fa", models.CharField(max_length=120)),
                ("source_code", models.CharField(max_length=64)),
                ("source_year", models.PositiveSmallIntegerField()),
                ("provenance_url", models.URLField(max_length=500)),
                ("imported_at", models.DateField()),
                ("reviewed", models.BooleanField(default=False)),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="neighborhoods",
                        to="catalog.district",
                    ),
                ),
            ],
            options={
                "ordering": ("name_fa",),
            },
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "property_type",
                    models.CharField(
                        blank=True,
                        choices=[("apartment", "آپارتمان"), ("house", "خانه"), ("villa", "ویلا")],
                        max_length=16,
                    ),
                ),
                ("area_sqm", models.PositiveIntegerField(blank=True, null=True)),
                ("room_count", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("construction_year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("floor", models.SmallIntegerField(blank=True, null=True)),
                ("total_floors", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("units_per_floor", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "parking",
                    models.CharField(
                        choices=[("unknown", "نامشخص"), ("present", "دارد"), ("absent", "ندارد")],
                        default="unknown",
                        max_length=8,
                    ),
                ),
                (
                    "elevator",
                    models.CharField(
                        choices=[("unknown", "نامشخص"), ("present", "دارد"), ("absent", "ندارد")],
                        default="unknown",
                        max_length=8,
                    ),
                ),
                (
                    "storage",
                    models.CharField(
                        choices=[("unknown", "نامشخص"), ("present", "دارد"), ("absent", "ندارد")],
                        default="unknown",
                        max_length=8,
                    ),
                ),
                (
                    "balcony",
                    models.CharField(
                        choices=[("unknown", "نامشخص"), ("present", "دارد"), ("absent", "ندارد")],
                        default="unknown",
                        max_length=8,
                    ),
                ),
                (
                    "furnished",
                    models.CharField(
                        choices=[("unknown", "نامشخص"), ("present", "دارد"), ("absent", "ندارد")],
                        default="unknown",
                        max_length=8,
                    ),
                ),
                ("heating", models.CharField(blank=True, max_length=120)),
                ("cooling", models.CharField(blank=True, max_length=120)),
                ("operator_location_notes", models.TextField(blank=True)),
                (
                    "latitude",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
                ),
                (
                    "longitude",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
                ),
                ("provenance_note", models.TextField(blank=True)),
                ("normalized_at", models.DateTimeField(blank=True, null=True)),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="properties",
                        to="catalog.city",
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="properties",
                        to="catalog.district",
                    ),
                ),
                (
                    "neighborhood",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="properties",
                        to="catalog.neighborhood",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RentalTerms",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("deposit_rial", models.PositiveBigIntegerField()),
                ("monthly_rent_rial", models.PositiveBigIntegerField()),
                (
                    "currency",
                    models.CharField(
                        choices=[("IRR", "ریال ایران")], default="IRR", editable=False, max_length=3
                    ),
                ),
                ("is_negotiable", models.BooleanField(default=False)),
                ("is_convertible", models.BooleanField(default=False)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("deposit_rial__gt", 0), ("monthly_rent_rial__gt", 0), _connector="OR"
                        ),
                        name="catalog_rental_terms_nonzero",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("currency", "IRR")), name="catalog_rental_terms_irr"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("domain", models.CharField(max_length=253, unique=True)),
                ("display_name", models.CharField(max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("is_builtin", models.BooleanField(default=False)),
                (
                    "outbound_policy",
                    models.CharField(
                        choices=[
                            ("direct_contact", "تماس مستقیم"),
                            ("external_link", "پیوند منبع"),
                            ("disabled", "غیرفعال"),
                        ],
                        max_length=24,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_builtin", True)),
                        fields=("is_builtin",),
                        name="catalog_single_builtin_source",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "پیش\u200cنویس"),
                            ("published", "منتشرشده"),
                            ("unavailable", "ناموجود"),
                            ("archived", "بایگانی\u200cشده"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("source_reference", models.CharField(blank=True, max_length=255)),
                ("source_claims", models.JSONField(blank=True, default=dict)),
                ("provenance_note", models.TextField(blank=True)),
                ("external_url", models.URLField(blank=True, max_length=1000)),
                ("direct_phone", models.CharField(blank=True, max_length=32)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("availability_confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("available_until", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="listings",
                        to="catalog.property",
                    ),
                ),
                (
                    "terms",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="listing",
                        to="catalog.rentalterms",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="listings",
                        to="catalog.source",
                    ),
                ),
            ],
            options={
                "ordering": ("-availability_confirmed_at", "id"),
            },
        ),
        migrations.AddConstraint(
            model_name="district",
            constraint=models.UniqueConstraint(
                fields=("city", "number"), name="catalog_unique_district"
            ),
        ),
        migrations.AddConstraint(
            model_name="neighborhood",
            constraint=models.UniqueConstraint(
                fields=("district", "name_fa"), name="catalog_unique_neighborhood"
            ),
        ),
    ]
