# Generated by Django 6.1 on 2026-09-17 17:56

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("common", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name_fa", models.CharField(max_length=120)),
                ("source_code", models.CharField(max_length=64)),
                ("source_year", models.PositiveSmallIntegerField()),
                ("provenance_url", models.URLField(max_length=500)),
                ("imported_at", models.DateField()),
                ("reviewed", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "cities",
            },
        ),
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "پیش\u200cنویس"),
                            ("pending", "در انتظار بررسی"),
                            ("published", "منتشرشده"),
                            ("expired", "منقضی\u200cشده"),
                            ("rejected", "ردشده"),
                            ("unavailable", "ناموجود"),
                            ("archived", "بایگانی\u200cشده"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("source_reference", models.CharField(blank=True, max_length=255)),
                ("source_claims", models.JSONField(blank=True, default=dict)),
                ("provenance_note", models.TextField(blank=True)),
                ("external_url", models.URLField(blank=True, max_length=1000)),
                ("external_media_url", models.URLField(blank=True, max_length=1000)),
                ("direct_phone", models.CharField(blank=True, max_length=32)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("availability_confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("available_until", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-availability_confirmed_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="PropertyMatchOperation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("backfill", "پس\u200cپرکردن اولیه"),
                            ("rescore", "امتیازدهی دوباره"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار"),
                            ("running", "در حال اجرا"),
                            ("completed", "تکمیل\u200cشده"),
                            ("failed", "ناموفق"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("candidates", "نامزدها"),
                            ("suggestions", "پیشنهادها"),
                            ("groups", "گروه\u200cها"),
                            ("completed", "تکمیل\u200cشده"),
                        ],
                        max_length=16,
                    ),
                ),
                ("scoring_version", models.CharField(max_length=64)),
                ("cursor", models.UUIDField(blank=True, null=True)),
                ("candidate_cursor", models.UUIDField(blank=True, null=True)),
                ("generation", models.PositiveIntegerField(default=0)),
                ("processed_targets", models.PositiveIntegerField(default=0)),
                ("evaluated_pairs", models.PositiveIntegerField(default=0)),
                ("active_suggestions", models.PositiveIntegerField(default=0)),
                ("measured_groups", models.PositiveIntegerField(default=0)),
                ("error_code", models.CharField(blank=True, max_length=120)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ("-started_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name_fa", models.CharField(max_length=120)),
                ("source_code", models.CharField(max_length=64)),
                ("source_year", models.PositiveSmallIntegerField()),
                ("provenance_url", models.URLField(max_length=500)),
                ("imported_at", models.DateField()),
                ("reviewed", models.BooleanField(default=False)),
                ("number", models.PositiveSmallIntegerField()),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="districts",
                        to="catalog.city",
                    ),
                ),
            ],
            options={
                "ordering": ("number",),
            },
        ),
        migrations.CreateModel(
            name="ListingImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                ("is_primary", models.BooleanField(default=False)),
                ("raw_content_sha256", models.CharField(blank=True, db_index=True, max_length=64)),
                (
                    "normalized_pixel_sha256",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("perceptual_dhash", models.CharField(blank=True, db_index=True, max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.listing",
                    ),
                ),
            ],
            options={
                "ordering": ("position",),
            },
        ),
        migrations.CreateModel(
            name="ListingImagePerceptualBucket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                ("value", models.CharField(max_length=1)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perceptual_buckets",
                        to="catalog.listingimage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ListingImageVariant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("small", "کوچک"), ("medium", "متوسط"), ("large", "بزرگ")],
                        max_length=8,
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="listing_variants",
                        to="common.mediaasset",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="catalog.listingimage",
                    ),
                ),
            ],
            options={
                "ordering": ("kind",),
            },
        ),
        migrations.CreateModel(
            name="ListingPriceObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("deposit_rial", models.PositiveBigIntegerField()),
                ("monthly_rent_rial", models.PositiveBigIntegerField()),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="catalog.listing",
                    ),
                ),
            ],
            options={
                "ordering": ("recorded_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="Neighborhood",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name_fa", models.CharField(max_length=120)),
                ("source_code", models.CharField(max_length=64)),
                ("source_year", models.PositiveSmallIntegerField()),
                ("provenance_url", models.URLField(max_length=500)),
                ("imported_at", models.DateField()),
                ("reviewed", models.BooleanField(default=False)),
                (
                    "center_latitude",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
                ),
                (
                    "center_longitude",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
                ),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="neighborhoods",
                        to="catalog.district",
                    ),
                ),
            ],
            options={
                "ordering": ("name_fa",),
            },
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "property_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("apartment", "آپارتمان"),
                            ("house", "خانه"),
                            ("villa", "ویلا"),
                            ("office", "دفتر اداری"),
                            ("shop", "مغازه"),
                            ("warehouse", "انبار"),
                            ("workshop", "کارگاه"),
                        ],
                        max_length=16,
                    ),
                ),
                ("area_sqm", models.PositiveIntegerField(blank=True, null=True)),
                ("room_count", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("construction_year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("floor", models.SmallIntegerField(blank=True, null=True)),
                ("total_floors", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("units_per_floor", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "parking",
                    models.CharField(
                        choices=[("unknown", "نامشخص"), ("present", "دارد"), ("absent", "ندارد")],
                        default="unknown",
                        max_length=8,
                    ),
                ),
                (
                    "elevator",
                    models.CharField(
                        choices=[("unknown", "نامشخص"), ("present", "دارد"), ("absent", "ندارد")],
                        default="unknown",
                        max_length=8,
                    ),
                ),
                (
                    "storage",
                    models.CharField(
                        choices=[("unknown", "نامشخص"), ("present", "دارد"), ("absent", "ندارد")],
                        default="unknown",
                        max_length=8,
                    ),
                ),
                (
                    "balcony",
                    models.CharField(
                        choices=[("unknown", "نامشخص"), ("present", "دارد"), ("absent", "ندارد")],
                        default="unknown",
                        max_length=8,
                    ),
                ),
                (
                    "furnished",
                    models.CharField(
                        choices=[("unknown", "نامشخص"), ("present", "دارد"), ("absent", "ندارد")],
                        default="unknown",
                        max_length=8,
                    ),
                ),
                ("heating", models.CharField(blank=True, max_length=120)),
                ("cooling", models.CharField(blank=True, max_length=120)),
                ("operator_location_notes", models.TextField(blank=True)),
                (
                    "latitude",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
                ),
                (
                    "longitude",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
                ),
                (
                    "approximate_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, editable=False, max_digits=9, null=True
                    ),
                ),
                (
                    "approximate_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, editable=False, max_digits=9, null=True
                    ),
                ),
                (
                    "location_precision",
                    models.CharField(
                        blank=True,
                        choices=[("approximate", "Approximate"), ("neighborhood", "Neighborhood")],
                        editable=False,
                        max_length=16,
                    ),
                ),
                (
                    "location_radius_meters",
                    models.PositiveIntegerField(blank=True, editable=False, null=True),
                ),
                ("provenance_note", models.TextField(blank=True)),
                ("normalized_at", models.DateTimeField(blank=True, null=True)),
                ("merged_at", models.DateTimeField(blank=True, editable=False, null=True)),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="properties",
                        to="catalog.city",
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="properties",
                        to="catalog.district",
                    ),
                ),
                (
                    "merged_into",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="merged_properties",
                        to="catalog.property",
                    ),
                ),
                (
                    "neighborhood",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="properties",
                        to="catalog.neighborhood",
                    ),
                ),
            ],
            options={
                "permissions": (("curate_catalog", "Can curate the Property catalog"),),
            },
        ),
        migrations.AddField(
            model_name="listing",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="listings",
                to="catalog.property",
            ),
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("saved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="catalog.property",
                    ),
                ),
            ],
            options={
                "ordering": ("-saved_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="PropertyGroupConsistencyMeasurement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("group_revision", models.CharField(max_length=64)),
                ("scoring_version", models.CharField(max_length=64)),
                ("listing_count", models.PositiveIntegerField()),
                ("pair_measurements", models.JSONField(default=list)),
                ("strongest_pair", models.JSONField(blank=True, null=True)),
                ("weakest_pair", models.JSONField(blank=True, null=True)),
                ("explicit_contradictions", models.JSONField(default=list)),
                ("needs_attention", models.BooleanField(default=False)),
                ("measured_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consistency_measurements",
                        to="catalog.property",
                    ),
                ),
            ],
            options={
                "ordering": ("-measured_at", "-id"),
            },
        ),
        migrations.AddField(
            model_name="property",
            name="current_consistency_measurement",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="catalog.propertygroupconsistencymeasurement",
            ),
        ),
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                ("retired_at", models.DateTimeField(blank=True, editable=False, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                ("is_primary", models.BooleanField(default=False)),
                ("reviewed_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.property",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_property_images",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("position",),
            },
        ),
        migrations.CreateModel(
            name="PropertyImageVariant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("small", "کوچک"), ("medium", "متوسط"), ("large", "بزرگ")],
                        max_length=8,
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="property_variants",
                        to="common.mediaasset",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="catalog.propertyimage",
                    ),
                ),
            ],
            options={
                "ordering": ("kind",),
            },
        ),
        migrations.CreateModel(
            name="PropertyMatchSuggestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار بررسی"),
                            ("approved", "تأییدشده"),
                            ("rejected", "ردشده"),
                            ("snoozed", "به تعویق افتاده"),
                            ("superseded", "جایگزین\u200cشده"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("score", models.PositiveSmallIntegerField()),
                ("band", models.CharField(max_length=16)),
                ("scoring_version", models.CharField(max_length=64)),
                ("evidence_fingerprint", models.CharField(max_length=64)),
                ("left_revision", models.CharField(max_length=64)),
                ("right_revision", models.CharField(max_length=64)),
                ("evidence", models.JSONField()),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("focused", "سنجش متمرکز"),
                            ("nightly", "آشتی شبانه"),
                            ("backfill", "پس\u200cپرکردن اولیه"),
                            ("rescore", "امتیازدهی دوباره"),
                        ],
                        max_length=16,
                    ),
                ),
                ("suppressed_evidence_fingerprint", models.CharField(blank=True, max_length=64)),
                ("snoozed_until", models.DateTimeField(blank=True, null=True)),
                ("first_suggested_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_evaluated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "left",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="left_match_suggestions",
                        to="catalog.property",
                    ),
                ),
                (
                    "rebased_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rebased_from",
                        to="catalog.propertymatchsuggestion",
                    ),
                ),
                (
                    "right",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="right_match_suggestions",
                        to="catalog.property",
                    ),
                ),
            ],
            options={
                "ordering": ("-score", "first_suggested_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="PropertyMatchClaim",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "left",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="left_match_claims",
                        to="catalog.property",
                    ),
                ),
                (
                    "right",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="right_match_claims",
                        to="catalog.property",
                    ),
                ),
                (
                    "suggestion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="claims",
                        to="catalog.propertymatchsuggestion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PropertyMatchSuggestionEvaluation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("score", models.PositiveSmallIntegerField()),
                ("band", models.CharField(max_length=16)),
                ("scoring_version", models.CharField(max_length=64)),
                ("evidence_fingerprint", models.CharField(max_length=64)),
                ("left_revision", models.CharField(max_length=64)),
                ("right_revision", models.CharField(max_length=64)),
                ("evidence", models.JSONField()),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("focused", "سنجش متمرکز"),
                            ("nightly", "آشتی شبانه"),
                            ("backfill", "پس\u200cپرکردن اولیه"),
                            ("rescore", "امتیازدهی دوباره"),
                        ],
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "suggestion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evaluations",
                        to="catalog.propertymatchsuggestion",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="PropertyMatchDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("operator_initiated", "آغازشده توسط کارشناس"),
                            ("administrative", "تعمیر مدیریتی"),
                            ("focused", "سنجش متمرکز"),
                            ("nightly", "آشتی شبانه"),
                            ("backfill", "پس\u200cپرکردن اولیه"),
                            ("rescore", "امتیازدهی دوباره"),
                        ],
                        default="operator_initiated",
                        editable=False,
                        max_length=24,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("same_property", "یک ملک"),
                            ("not_same_property", "دو ملک متفاوت"),
                            ("snoozed", "تعویق"),
                        ],
                        default="same_property",
                        max_length=24,
                    ),
                ),
                ("evaluation_snapshot", models.JSONField(blank=True, default=dict)),
                ("before_revision", models.CharField(max_length=64)),
                ("after_revision", models.CharField(max_length=64)),
                ("evidence", models.JSONField()),
                ("after_snapshot", models.JSONField()),
                ("selected_facts", models.JSONField()),
                ("selected_image_ids", models.JSONField()),
                ("affected_listing_ids", models.JSONField()),
                ("request_digest", models.CharField(max_length=64)),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "claim",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="catalog.propertymatchclaim"
                    ),
                ),
                (
                    "redundant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="redundant_decisions",
                        to="catalog.property",
                    ),
                ),
                (
                    "survivor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="match_decisions",
                        to="catalog.property",
                    ),
                ),
                (
                    "suggestion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decisions",
                        to="catalog.propertymatchsuggestion",
                    ),
                ),
                (
                    "evaluation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decisions",
                        to="catalog.propertymatchsuggestionevaluation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PropertyPartitionClaim",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("selected_listing_ids", models.JSONField(default=list)),
                ("revision", models.CharField(max_length=64)),
                ("expires_at", models.DateTimeField()),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="partition_claims",
                        to="catalog.property",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PropertyPartitionDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("operator_initiated", "آغازشده توسط کارشناس"),
                            ("administrative", "تعمیر مدیریتی"),
                            ("focused", "سنجش متمرکز"),
                            ("nightly", "آشتی شبانه"),
                            ("backfill", "پس\u200cپرکردن اولیه"),
                            ("rescore", "امتیازدهی دوباره"),
                        ],
                        default="operator_initiated",
                        editable=False,
                        max_length=24,
                    ),
                ),
                ("restored_historical_property", models.BooleanField(default=False)),
                ("selected_listing_ids", models.JSONField(default=list)),
                ("evaluation_snapshot", models.JSONField(blank=True, default=dict)),
                ("before_revision", models.CharField(max_length=64)),
                ("after_revision", models.CharField(max_length=64)),
                ("evidence", models.JSONField()),
                ("after_snapshot", models.JSONField()),
                ("selected_facts", models.JSONField(default=dict)),
                ("selected_image_ids", models.JSONField(default=list)),
                ("suppression_fingerprint", models.CharField(max_length=64)),
                ("request_digest", models.CharField(max_length=64)),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "claim",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.propertypartitionclaim",
                    ),
                ),
                (
                    "separated_property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="partition_result_decisions",
                        to="catalog.property",
                    ),
                ),
                (
                    "source_property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="partition_source_decisions",
                        to="catalog.property",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ListingGroupingEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("attach", "اتصال"), ("split", "تفکیک"), ("merge", "ادغام")],
                        max_length=12,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grouping_events",
                        to="catalog.listing",
                    ),
                ),
                (
                    "from_property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outgoing_grouping_events",
                        to="catalog.property",
                    ),
                ),
                (
                    "to_property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming_grouping_events",
                        to="catalog.property",
                    ),
                ),
                (
                    "decision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grouping_events",
                        to="catalog.propertymatchdecision",
                    ),
                ),
                (
                    "partition_decision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grouping_events",
                        to="catalog.propertypartitiondecision",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="RentalTerms",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("deposit_rial", models.PositiveBigIntegerField()),
                ("monthly_rent_rial", models.PositiveBigIntegerField()),
                (
                    "currency",
                    models.CharField(
                        choices=[("IRR", "ریال ایران")], default="IRR", editable=False, max_length=3
                    ),
                ),
                ("is_negotiable", models.BooleanField(default=False)),
                ("is_convertible", models.BooleanField(default=False)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("deposit_rial__gt", 0), ("monthly_rent_rial__gt", 0), _connector="OR"
                        ),
                        name="catalog_rental_terms_nonzero",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("currency", "IRR")), name="catalog_rental_terms_irr"
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="listing",
            name="terms",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="listing",
                to="catalog.rentalterms",
            ),
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                ("processing_paused", models.BooleanField(db_default=False, default=False)),
                ("processing_revision", models.PositiveIntegerField(db_default=0, default=0)),
                ("crawl_interval_hours", models.PositiveIntegerField(db_default=0, default=0)),
                ("crawl_schedule_revision", models.PositiveIntegerField(db_default=0, default=0)),
                ("next_crawl_at", models.DateTimeField(blank=True, null=True)),
                ("crawl_schedule_error", models.TextField(blank=True, db_default="", default="")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("domain", models.CharField(max_length=253, unique=True)),
                ("display_name", models.CharField(max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("is_builtin", models.BooleanField(default=False)),
                (
                    "outbound_policy",
                    models.CharField(
                        choices=[
                            ("direct_contact", "تماس مستقیم"),
                            ("external_link", "پیوند منبع"),
                            ("disabled", "غیرفعال"),
                        ],
                        max_length=24,
                    ),
                ),
                ("allows_external_media", models.BooleanField(default=False)),
                ("responsibility_revision", models.PositiveIntegerField(db_default=0, default=0)),
                (
                    "responsible_operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responsible_sources",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("property_view", "بازدید ملک"),
                            ("external_continuation", "ادامه در منبع بیرونی"),
                            ("phone_reveal", "نمایش شماره تماس"),
                        ],
                        max_length=24,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_events",
                        to="catalog.listing",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_events",
                        to="catalog.property",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_events",
                        to="catalog.source",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "id"),
            },
        ),
        migrations.AddField(
            model_name="listing",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="listings",
                to="catalog.source",
            ),
        ),
        migrations.AddConstraint(
            model_name="district",
            constraint=models.UniqueConstraint(
                fields=("city", "number"), name="catalog_unique_district"
            ),
        ),
        migrations.AddConstraint(
            model_name="listingimage",
            constraint=models.UniqueConstraint(
                fields=("listing", "position"), name="unique_listing_image_position"
            ),
        ),
        migrations.AddConstraint(
            model_name="listingimage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("listing",),
                name="one_primary_image_per_listing",
            ),
        ),
        migrations.AddIndex(
            model_name="listingimageperceptualbucket",
            index=models.Index(fields=["position", "value"], name="catalog_dhash_bucket_lookup"),
        ),
        migrations.AddConstraint(
            model_name="listingimageperceptualbucket",
            constraint=models.UniqueConstraint(
                fields=("image", "position"), name="catalog_unique_listing_image_dhash_bucket"
            ),
        ),
        migrations.AddConstraint(
            model_name="listingimagevariant",
            constraint=models.UniqueConstraint(
                fields=("image", "kind"), name="unique_listing_image_variant"
            ),
        ),
        migrations.AddConstraint(
            model_name="neighborhood",
            constraint=models.UniqueConstraint(
                fields=("district", "name_fa"), name="catalog_unique_neighborhood"
            ),
        ),
        migrations.AddConstraint(
            model_name="favorite",
            constraint=models.UniqueConstraint(
                fields=("account", "property"), name="catalog_unique_favorite_per_account_property"
            ),
        ),
        migrations.AddConstraint(
            model_name="propertygroupconsistencymeasurement",
            constraint=models.UniqueConstraint(
                fields=("property", "group_revision", "scoring_version"),
                name="catalog_unique_group_consistency_measurement",
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(fields=["latitude", "longitude"], name="catalog_prop_coords"),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["city", "property_type", "area_sqm"], name="catalog_prop_city_facts"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["neighborhood", "property_type", "area_sqm"],
                name="catalog_prop_neigh_facts",
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["total_floors", "units_per_floor"], name="catalog_prop_build_facts"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["floor", "construction_year"], name="catalog_prop_floor_year"
            ),
        ),
        migrations.AddConstraint(
            model_name="propertyimage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("retired_at__isnull", True)),
                fields=("property", "position"),
                name="unique_property_image_position",
            ),
        ),
        migrations.AddConstraint(
            model_name="propertyimage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True), ("retired_at__isnull", True)),
                fields=("property",),
                name="one_primary_image_per_property",
            ),
        ),
        migrations.AddConstraint(
            model_name="propertyimagevariant",
            constraint=models.UniqueConstraint(
                fields=("image", "kind"), name="unique_property_image_variant"
            ),
        ),
        migrations.AddConstraint(
            model_name="propertymatchsuggestion",
            constraint=models.CheckConstraint(
                condition=models.Q(("left_id__lt", models.F("right_id"))),
                name="catalog_match_suggestion_ordered_pair",
            ),
        ),
        migrations.AddConstraint(
            model_name="propertymatchsuggestion",
            constraint=models.UniqueConstraint(
                fields=("left", "right"), name="catalog_unique_match_suggestion_pair"
            ),
        ),
        migrations.AddConstraint(
            model_name="listinggroupingevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("decision__isnull", False),
                    ("partition_decision__isnull", False),
                    _negated=True,
                ),
                name="catalog_grouping_event_one_decision_kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="source",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_builtin", True)),
                fields=("is_builtin",),
                name="catalog_single_builtin_source",
            ),
        ),
    ]
