# Generated by Django 6.1 on 2026-08-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="state",
            field=models.CharField(
                choices=[
                    ("draft", "پیش\u200cنویس"),
                    ("pending", "در انتظار بررسی"),
                    ("published", "منتشرشده"),
                    ("rejected", "ردشده"),
                    ("unavailable", "ناموجود"),
                    ("archived", "بایگانی\u200cشده"),
                ],
                default="draft",
                max_length=16,
            ),
        ),
    ]
