# Generated by Django 6.1 on 2026-08-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_property_merged_at_property_merged_into_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="external_media_url",
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="source",
            name="allows_external_media",
            field=models.BooleanField(default=False),
        ),
    ]
