# Generated by Django 6.1 on 2026-08-22 16:20

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_listing_external_media_url_and_more"),
        ("submissions", "0003_share_processed_media_assets"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListingImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.listing",
                    ),
                ),
            ],
            options={
                "ordering": ("position",),
            },
        ),
        migrations.CreateModel(
            name="ListingImageVariant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("small", "کوچک"), ("medium", "متوسط"), ("large", "بزرگ")],
                        max_length=8,
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="listing_variants",
                        to="submissions.mediaasset",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="catalog.listingimage",
                    ),
                ),
            ],
            options={
                "ordering": ("kind",),
            },
        ),
        migrations.AddConstraint(
            model_name="listingimage",
            constraint=models.UniqueConstraint(
                fields=("listing", "position"), name="unique_listing_image_position"
            ),
        ),
        migrations.AddConstraint(
            model_name="listingimage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("listing",),
                name="one_primary_image_per_listing",
            ),
        ),
        migrations.AddConstraint(
            model_name="listingimagevariant",
            constraint=models.UniqueConstraint(
                fields=("image", "kind"), name="unique_listing_image_variant"
            ),
        ),
    ]
