# Generated by Django 6.1 on 2026-08-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0008_alter_property_property_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="property_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("apartment", "آپارتمان"),
                    ("house", "خانه"),
                    ("villa", "ویلا"),
                    ("office", "دفتر اداری"),
                    ("shop", "مغازه"),
                    ("warehouse", "انبار"),
                    ("workshop", "کارگاه"),
                ],
                max_length=16,
            ),
        ),
    ]
