# Generated by Django 6.1 on 2026-08-26 13:27

import hashlib
import hmac
import math
from decimal import Decimal

from django.conf import settings
from django.db import migrations, models


def populate_existing_approximations(apps, _schema_editor):
    property_model = apps.get_model("catalog", "Property")
    for property_ in property_model.objects.filter(
        latitude__isnull=False, longitude__isnull=False
    ).iterator():
        digest = hmac.new(settings.SECRET_KEY.encode(), property_.id.bytes, hashlib.sha256).digest()
        angle = int.from_bytes(digest[:8], "big") / (2**64) * math.tau
        distance = 180 + int.from_bytes(digest[8:16], "big") / (2**64) * 140
        latitude = float(property_.latitude)
        longitude = float(property_.longitude)
        latitude_offset = math.cos(angle) * distance / 6_371_000
        longitude_offset = (
            math.sin(angle) * distance / (6_371_000 * math.cos(math.radians(latitude)))
        )
        property_.approximate_latitude = Decimal(f"{latitude + math.degrees(latitude_offset):.6f}")
        property_.approximate_longitude = Decimal(
            f"{longitude + math.degrees(longitude_offset):.6f}"
        )
        property_.location_precision = "approximate"
        property_.location_radius_meters = 500
        property_.save(
            update_fields=(
                "approximate_latitude",
                "approximate_longitude",
                "location_precision",
                "location_radius_meters",
            )
        )


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0009_alter_property_property_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="neighborhood",
            name="center_latitude",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="neighborhood",
            name="center_longitude",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="approximate_latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, editable=False, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="approximate_longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, editable=False, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="location_precision",
            field=models.CharField(
                blank=True,
                choices=[("approximate", "Approximate"), ("neighborhood", "Neighborhood")],
                editable=False,
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="location_radius_meters",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.RunPython(populate_existing_approximations, migrations.RunPython.noop),
    ]
