# Generated by Django 6.1 on 2026-08-26

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def promote_images_from_initial_operator_reviews(apps, _schema_editor):
    listing_image_model = apps.get_model("catalog", "ListingImage")
    property_image_model = apps.get_model("catalog", "PropertyImage")
    property_variant_model = apps.get_model("catalog", "PropertyImageVariant")
    submission_event_model = apps.get_model("submissions", "SubmissionEvent")
    reviewed_properties = set()
    publication_reviews = (
        submission_event_model.objects
        .filter(
            new_state="published",
            corrects__isnull=True,
            submission__listing__isnull=False,
        )
        .select_related("submission__listing")
        .order_by("created_at", "id")
    )
    for review in publication_reviews.iterator(chunk_size=100):
        listing = review.submission.listing
        property_id = listing.property_id
        if property_id in reviewed_properties:
            continue
        listing_image = (
            listing_image_model.objects
            .filter(listing_id=listing.id, is_primary=True)
            .prefetch_related("variants")
            .first()
        )
        if listing_image is None:
            continue
        reviewed_properties.add(property_id)
        property_image = property_image_model.objects.create(
            property_id=property_id,
            position=0,
            is_primary=True,
            reviewed_at=review.created_at,
            reviewed_by_id=review.actor_id,
        )
        property_variant_model.objects.bulk_create([
            property_variant_model(
                image=property_image,
                kind=variant.kind,
                asset_id=variant.asset_id,
            )
            for variant in listing_image.variants.all()
        ])


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0011_merge_favorite_location"),
        ("submissions", "0010_submission_exact_latitude_submission_exact_longitude"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                ("is_primary", models.BooleanField(default=False)),
                ("reviewed_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.property",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_property_images",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ("position",)},
        ),
        migrations.CreateModel(
            name="PropertyImageVariant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("small", "کوچک"),
                            ("medium", "متوسط"),
                            ("large", "بزرگ"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="property_variants",
                        to="submissions.mediaasset",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="catalog.propertyimage",
                    ),
                ),
            ],
            options={"ordering": ("kind",)},
        ),
        migrations.RunPython(
            promote_images_from_initial_operator_reviews,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="propertyimage",
            constraint=models.UniqueConstraint(
                fields=("property", "position"),
                name="unique_property_image_position",
            ),
        ),
        migrations.AddConstraint(
            model_name="propertyimage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("property",),
                name="one_primary_image_per_property",
            ),
        ),
        migrations.AddConstraint(
            model_name="propertyimagevariant",
            constraint=models.UniqueConstraint(
                fields=("image", "kind"),
                name="unique_property_image_variant",
            ),
        ),
    ]
