# Generated by Django 6.1 on 2026-09-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0015_source_responsibility_revision_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="processing_paused",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name="source",
            name="processing_revision",
            field=models.PositiveIntegerField(db_default=0, default=0),
        ),
    ]
