# Generated by Django 6.1 on 2026-09-08 05:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def record_current_prices(apps, schema_editor):
    Listing = apps.get_model("catalog", "Listing")
    Observation = apps.get_model("catalog", "ListingPriceObservation")
    database = schema_editor.connection.alias
    observed_at = django.utils.timezone.now()
    batch = []
    for listing in (
        Listing.objects
        .using(database)
        .filter(state="published")
        .select_related("terms")
        .iterator(chunk_size=500)
    ):
        batch.append(
            Observation(
                listing_id=listing.pk,
                recorded_at=observed_at,
                deposit_rial=listing.terms.deposit_rial,
                monthly_rent_rial=listing.terms.monthly_rent_rial,
            )
        )
        if len(batch) == 500:
            Observation.objects.using(database).bulk_create(batch)
            batch = []
    Observation.objects.using(database).bulk_create(batch)


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0016_source_processing_paused_source_processing_revision"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListingPriceObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("deposit_rial", models.PositiveBigIntegerField()),
                ("monthly_rent_rial", models.PositiveBigIntegerField()),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="catalog.listing",
                    ),
                ),
            ],
            options={
                "ordering": ("recorded_at", "id"),
            },
        ),
        migrations.RunPython(record_current_prices, migrations.RunPython.noop),
    ]
