# Generated by Django 6.1 on 2026-09-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0017_listingpriceobservation"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="crawl_interval_hours",
            field=models.PositiveIntegerField(db_default=0, default=0),
        ),
        migrations.AddField(
            model_name="source",
            name="crawl_schedule_error",
            field=models.TextField(blank=True, db_default="", default=""),
        ),
        migrations.AddField(
            model_name="source",
            name="crawl_schedule_revision",
            field=models.PositiveIntegerField(db_default=0, default=0),
        ),
        migrations.AddField(
            model_name="source",
            name="next_crawl_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
