# Generated by Django 6.1 on 2026-09-12 10:36

from django.db import migrations


def create_catalog_curator_group(apps, schema_editor):
    content_type_model = apps.get_model("contenttypes", "ContentType")
    group_model = apps.get_model("auth", "Group")
    permission_model = apps.get_model("auth", "Permission")
    content_type, _ = content_type_model.objects.get_or_create(
        app_label="catalog", model="property"
    )
    permission, _ = permission_model.objects.get_or_create(
        content_type=content_type,
        codename="curate_catalog",
        defaults={"name": "Can curate the Property catalog"},
    )
    group, _ = group_model.objects.get_or_create(name="Catalog Curator")
    group.permissions.add(permission)


def remove_catalog_curator_group(apps, schema_editor):
    apps.get_model("auth", "Group").objects.filter(name="Catalog Curator").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("catalog", "0018_source_crawl_interval_hours_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="property",
            options={"permissions": (("curate_catalog", "Can curate the Property catalog"),)},
        ),
        migrations.RunPython(create_catalog_curator_group, remove_catalog_curator_group),
    ]
