# Generated by Django 6.1 on 2026-09-12 12:10

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0020_listingimage_normalized_pixel_sha256_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyMatchClaim",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("expires_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="PropertyMatchDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "origin",
                    models.CharField(default="operator_initiated", editable=False, max_length=24),
                ),
                ("before_revision", models.CharField(max_length=64)),
                ("after_revision", models.CharField(max_length=64)),
                ("evidence", models.JSONField()),
                ("after_snapshot", models.JSONField()),
                ("selected_facts", models.JSONField()),
                ("selected_image_ids", models.JSONField()),
                ("affected_listing_ids", models.JSONField()),
                ("request_digest", models.CharField(max_length=64)),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="propertyimage",
            name="unique_property_image_position",
        ),
        migrations.RemoveConstraint(
            model_name="propertyimage",
            name="one_primary_image_per_property",
        ),
        migrations.AddField(
            model_name="propertyimage",
            name="retired_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name="propertyimage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("retired_at__isnull", True)),
                fields=("property", "position"),
                name="unique_property_image_position",
            ),
        ),
        migrations.AddConstraint(
            model_name="propertyimage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True), ("retired_at__isnull", True)),
                fields=("property",),
                name="one_primary_image_per_property",
            ),
        ),
        migrations.AddField(
            model_name="propertymatchclaim",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="propertymatchclaim",
            name="left",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="left_match_claims",
                to="catalog.property",
            ),
        ),
        migrations.AddField(
            model_name="propertymatchclaim",
            name="right",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="right_match_claims",
                to="catalog.property",
            ),
        ),
        migrations.AddField(
            model_name="propertymatchdecision",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="propertymatchdecision",
            name="claim",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, to="catalog.propertymatchclaim"
            ),
        ),
        migrations.AddField(
            model_name="propertymatchdecision",
            name="redundant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="redundant_decisions",
                to="catalog.property",
            ),
        ),
        migrations.AddField(
            model_name="propertymatchdecision",
            name="survivor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="match_decisions",
                to="catalog.property",
            ),
        ),
        migrations.AddField(
            model_name="listinggroupingevent",
            name="decision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="grouping_events",
                to="catalog.propertymatchdecision",
            ),
        ),
    ]
