# Generated by Django 6.1 on 2026-09-12 13:59

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0021_manual_property_match_decisions"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyMatchSuggestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار بررسی"),
                            ("superseded", "جایگزین\u200cشده"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("score", models.PositiveSmallIntegerField()),
                ("band", models.CharField(max_length=16)),
                ("scoring_version", models.CharField(max_length=64)),
                ("evidence_fingerprint", models.CharField(max_length=64)),
                ("left_revision", models.CharField(max_length=64)),
                ("right_revision", models.CharField(max_length=64)),
                ("evidence", models.JSONField()),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("focused", "سنجش متمرکز"),
                            ("nightly", "آشتی شبانه"),
                            ("rescore", "امتیازدهی دوباره"),
                        ],
                        max_length=16,
                    ),
                ),
                ("first_suggested_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_evaluated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "left",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="left_match_suggestions",
                        to="catalog.property",
                    ),
                ),
                (
                    "right",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="right_match_suggestions",
                        to="catalog.property",
                    ),
                ),
            ],
            options={
                "ordering": ("-score", "first_suggested_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="PropertyMatchSuggestionEvaluation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("score", models.PositiveSmallIntegerField()),
                ("band", models.CharField(max_length=16)),
                ("scoring_version", models.CharField(max_length=64)),
                ("evidence_fingerprint", models.CharField(max_length=64)),
                ("left_revision", models.CharField(max_length=64)),
                ("right_revision", models.CharField(max_length=64)),
                ("evidence", models.JSONField()),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("focused", "سنجش متمرکز"),
                            ("nightly", "آشتی شبانه"),
                            ("rescore", "امتیازدهی دوباره"),
                        ],
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "suggestion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evaluations",
                        to="catalog.propertymatchsuggestion",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.AddConstraint(
            model_name="propertymatchsuggestion",
            constraint=models.CheckConstraint(
                condition=models.Q(("left_id__lt", models.F("right_id"))),
                name="catalog_match_suggestion_ordered_pair",
            ),
        ),
        migrations.AddConstraint(
            model_name="propertymatchsuggestion",
            constraint=models.UniqueConstraint(
                fields=("left", "right"), name="catalog_unique_match_suggestion_pair"
            ),
        ),
    ]
