# Generated by Django 6.1 on 2026-09-12 14:41

import django.db.models.deletion
from django.db import migrations, models


def populate_perceptual_buckets(apps, schema_editor):
    ListingImage = apps.get_model("catalog", "ListingImage")
    Bucket = apps.get_model("catalog", "ListingImagePerceptualBucket")
    buckets = []
    for image in ListingImage.objects.exclude(perceptual_dhash="").iterator(chunk_size=500):
        if len(image.perceptual_dhash) != 16:
            continue
        buckets.extend(
            Bucket(image_id=image.pk, position=position, value=value)
            for position, value in enumerate(image.perceptual_dhash)
        )
        if len(buckets) >= 8_000:
            Bucket.objects.bulk_create(buckets, batch_size=8_000)
            buckets.clear()
    Bucket.objects.bulk_create(buckets, batch_size=8_000)


def clear_perceptual_buckets(apps, schema_editor):
    apps.get_model("catalog", "ListingImagePerceptualBucket").objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0022_propertymatchsuggestion_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListingImagePerceptualBucket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                ("value", models.CharField(max_length=1)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perceptual_buckets",
                        to="catalog.listingimage",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["position", "value"], name="catalog_dhash_bucket_lookup")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("image", "position"),
                        name="catalog_unique_listing_image_dhash_bucket",
                    )
                ],
            },
        ),
        migrations.RunPython(populate_perceptual_buckets, clear_perceptual_buckets),
    ]
