# Generated by Django 6.1 on 2026-09-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0023_listingimageperceptualbucket"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="property",
            index=models.Index(fields=["latitude", "longitude"], name="catalog_prop_coords"),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["city", "property_type", "area_sqm"], name="catalog_prop_city_facts"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["neighborhood", "property_type", "area_sqm"],
                name="catalog_prop_neigh_facts",
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["total_floors", "units_per_floor"], name="catalog_prop_build_facts"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["floor", "construction_year"], name="catalog_prop_floor_year"
            ),
        ),
    ]
