# Generated by Django 6.1 on 2026-09-12 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0024_property_catalog_prop_coords_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertymatchclaim",
            name="suggestion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="claims",
                to="catalog.propertymatchsuggestion",
            ),
        ),
        migrations.AddField(
            model_name="propertymatchdecision",
            name="evaluation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="decisions",
                to="catalog.propertymatchsuggestionevaluation",
            ),
        ),
        migrations.AddField(
            model_name="propertymatchdecision",
            name="evaluation_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="propertymatchdecision",
            name="outcome",
            field=models.CharField(
                choices=[
                    ("same_property", "یک ملک"),
                    ("not_same_property", "دو ملک متفاوت"),
                    ("snoozed", "تعویق"),
                ],
                default="same_property",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="propertymatchdecision",
            name="suggestion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="decisions",
                to="catalog.propertymatchsuggestion",
            ),
        ),
        migrations.AddField(
            model_name="propertymatchsuggestion",
            name="snoozed_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="propertymatchsuggestion",
            name="suppressed_evidence_fingerprint",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="propertymatchdecision",
            name="redundant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="redundant_decisions",
                to="catalog.property",
            ),
        ),
        migrations.AlterField(
            model_name="propertymatchdecision",
            name="survivor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="match_decisions",
                to="catalog.property",
            ),
        ),
        migrations.AlterField(
            model_name="propertymatchsuggestion",
            name="state",
            field=models.CharField(
                choices=[
                    ("pending", "در انتظار بررسی"),
                    ("approved", "تأییدشده"),
                    ("rejected", "ردشده"),
                    ("snoozed", "به تعویق افتاده"),
                    ("superseded", "جایگزین\u200cشده"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
    ]
