# Generated by Django 6.1 on 2026-09-12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0025_propertymatchclaim_suggestion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertymatchsuggestion",
            name="rebased_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rebased_from",
                to="catalog.propertymatchsuggestion",
            ),
        ),
    ]
