# Generated by Django 6.1 on 2026-09-13 04:57

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0026_propertymatchsuggestion_rebased_to"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyGroupConsistencyMeasurement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("group_revision", models.CharField(max_length=64)),
                ("scoring_version", models.CharField(max_length=64)),
                ("listing_count", models.PositiveIntegerField()),
                ("pair_measurements", models.JSONField(default=list)),
                ("strongest_pair", models.JSONField(blank=True, null=True)),
                ("weakest_pair", models.JSONField(blank=True, null=True)),
                ("explicit_contradictions", models.JSONField(default=list)),
                ("needs_attention", models.BooleanField(default=False)),
                ("measured_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consistency_measurements",
                        to="catalog.property",
                    ),
                ),
            ],
            options={
                "ordering": ("-measured_at", "-id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("property", "group_revision", "scoring_version"),
                        name="catalog_unique_group_consistency_measurement",
                    )
                ],
            },
        ),
    ]
