# Generated by Django 6.1 on 2026-09-13 06:11

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0027_propertygroupconsistencymeasurement"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyPartitionClaim",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("selected_listing_ids", models.JSONField(default=list)),
                ("revision", models.CharField(max_length=64)),
                ("expires_at", models.DateTimeField()),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="partition_claims",
                        to="catalog.property",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PropertyPartitionDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("restored_historical_property", models.BooleanField(default=False)),
                ("selected_listing_ids", models.JSONField(default=list)),
                ("before_revision", models.CharField(max_length=64)),
                ("after_revision", models.CharField(max_length=64)),
                ("evidence", models.JSONField()),
                ("after_snapshot", models.JSONField()),
                ("selected_facts", models.JSONField(default=dict)),
                ("selected_image_ids", models.JSONField(default=list)),
                ("suppression_fingerprint", models.CharField(max_length=64)),
                ("request_digest", models.CharField(max_length=64)),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "claim",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.propertypartitionclaim",
                    ),
                ),
                (
                    "separated_property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="partition_result_decisions",
                        to="catalog.property",
                    ),
                ),
                (
                    "source_property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="partition_source_decisions",
                        to="catalog.property",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="listinggroupingevent",
            name="partition_decision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="grouping_events",
                to="catalog.propertypartitiondecision",
            ),
        ),
        migrations.AddConstraint(
            model_name="listinggroupingevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("decision__isnull", False),
                    ("partition_decision__isnull", False),
                    _negated=True,
                ),
                name="catalog_grouping_event_one_decision_kind",
            ),
        ),
    ]
