# Generated by Django 6.1 on 2026-09-13

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("catalog", "0028_propertypartitionclaim_propertypartitiondecision_and_more")]

    operations = [
        migrations.CreateModel(
            name="PropertyMatchOperation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("backfill", "پس‌پرکردن اولیه"),
                            ("rescore", "امتیازدهی دوباره"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار"),
                            ("running", "در حال اجرا"),
                            ("completed", "تکمیل‌شده"),
                            ("failed", "ناموفق"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("candidates", "نامزدها"),
                            ("suggestions", "پیشنهادها"),
                            ("groups", "گروه‌ها"),
                            ("completed", "تکمیل‌شده"),
                        ],
                        max_length=16,
                    ),
                ),
                ("scoring_version", models.CharField(max_length=64)),
                ("cursor", models.UUIDField(blank=True, null=True)),
                ("candidate_cursor", models.UUIDField(blank=True, null=True)),
                ("generation", models.PositiveIntegerField(default=0)),
                ("processed_targets", models.PositiveIntegerField(default=0)),
                ("evaluated_pairs", models.PositiveIntegerField(default=0)),
                ("active_suggestions", models.PositiveIntegerField(default=0)),
                ("measured_groups", models.PositiveIntegerField(default=0)),
                ("error_code", models.CharField(blank=True, max_length=120)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={"ordering": ("-started_at", "-id")},
        ),
        migrations.AlterField(
            model_name="propertymatchsuggestion",
            name="origin",
            field=models.CharField(
                choices=[
                    ("focused", "سنجش متمرکز"),
                    ("nightly", "آشتی شبانه"),
                    ("backfill", "پس‌پرکردن اولیه"),
                    ("rescore", "امتیازدهی دوباره"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="propertymatchsuggestionevaluation",
            name="origin",
            field=models.CharField(
                choices=[
                    ("focused", "سنجش متمرکز"),
                    ("nightly", "آشتی شبانه"),
                    ("backfill", "پس‌پرکردن اولیه"),
                    ("rescore", "امتیازدهی دوباره"),
                ],
                max_length=16,
            ),
        ),
    ]
