# Generated by Django 6.1 on 2026-09-13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("catalog", "0029_propertymatchoperation")]

    operations = [
        migrations.AddField(
            model_name="propertypartitiondecision",
            name="evaluation_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="propertypartitiondecision",
            name="origin",
            field=models.CharField(
                choices=[
                    ("operator_initiated", "آغازشده توسط کارشناس"),
                    ("administrative", "تعمیر مدیریتی"),
                    ("focused", "سنجش متمرکز"),
                    ("nightly", "آشتی شبانه"),
                    ("backfill", "پس‌پرکردن اولیه"),
                    ("rescore", "امتیازدهی دوباره"),
                ],
                default="operator_initiated",
                editable=False,
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="propertymatchdecision",
            name="origin",
            field=models.CharField(
                choices=[
                    ("operator_initiated", "آغازشده توسط کارشناس"),
                    ("administrative", "تعمیر مدیریتی"),
                    ("focused", "سنجش متمرکز"),
                    ("nightly", "آشتی شبانه"),
                    ("backfill", "پس‌پرکردن اولیه"),
                    ("rescore", "امتیازدهی دوباره"),
                ],
                default="operator_initiated",
                editable=False,
                max_length=24,
            ),
        ),
    ]
