# Generated by Django 6.1 on 2026-09-14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0030_partition_decision_administrative_audit"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="current_consistency_measurement",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="catalog.propertygroupconsistencymeasurement",
            ),
        ),
    ]
