# Generated by Django 6.1 on 2026-09-17 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0031_property_current_consistency_measurement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertygroupconsistencymeasurement",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consistency_measurements",
                to="catalog.property",
            ),
        ),
    ]
