# Generated by Django 6.1 on 2026-08-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_create_operator_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="anonymized_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
