# Generated by Django 6.1 on 2026-08-26

from django.db import migrations, models


def preserve_existing_submitter_behavior(apps, _schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.update(is_submitter=True)


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_user_anonymized_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_submitter",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.RunPython(preserve_existing_submitter_behavior, migrations.RunPython.noop),
    ]
