# Generated by Django 6.1 on 2026-08-31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_user_phone_user_phone_verified_at_alter_user_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="phoneverificationchallenge",
            name="grants_submitter_eligibility",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="submitter_onboarding_path",
            field=models.CharField(
                blank=True,
                choices=[("submission", "Submission"), ("source_proposal", "Source Proposal")],
                max_length=16,
                null=True,
            ),
        ),
    ]
