# Generated by Django 6.1 on 2026-08-22 10:59

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0002_alter_listing_state"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("owner", "مالک"), ("agent", "نماینده مالک")], max_length=8
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("draft", "پیش\u200cنویس")], default="draft", max_length=16
                    ),
                ),
                (
                    "current_step",
                    models.CharField(
                        choices=[
                            ("location", "نشانی ملک"),
                            ("property_facts", "مشخصات ملک"),
                            ("rental_terms", "شرایط اجاره"),
                            ("features_description", "امکانات و توضیحات"),
                            ("images", "تصاویر"),
                            ("contact", "اطلاعات تماس"),
                            ("review", "بازبینی"),
                        ],
                        default="location",
                        max_length=32,
                    ),
                ),
                ("media_complete", models.BooleanField(default=False, editable=False)),
                ("address", models.TextField(blank=True)),
                (
                    "property_type",
                    models.CharField(
                        blank=True,
                        choices=[("apartment", "آپارتمان"), ("house", "خانه"), ("villa", "ویلا")],
                        max_length=16,
                    ),
                ),
                ("area_sqm", models.PositiveIntegerField(blank=True, null=True)),
                ("room_count", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("construction_year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("floor", models.SmallIntegerField(blank=True, null=True)),
                ("total_floors", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("units_per_floor", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("deposit_rial", models.PositiveBigIntegerField(blank=True, null=True)),
                ("monthly_rent_rial", models.PositiveBigIntegerField(blank=True, null=True)),
                ("is_negotiable", models.BooleanField(default=False)),
                ("is_convertible", models.BooleanField(default=False)),
                (
                    "parking",
                    models.CharField(
                        choices=[("unknown", "نامشخص"), ("present", "دارد"), ("absent", "ندارد")],
                        default="unknown",
                        max_length=8,
                    ),
                ),
                (
                    "elevator",
                    models.CharField(
                        choices=[("unknown", "نامشخص"), ("present", "دارد"), ("absent", "ندارد")],
                        default="unknown",
                        max_length=8,
                    ),
                ),
                (
                    "storage",
                    models.CharField(
                        choices=[("unknown", "نامشخص"), ("present", "دارد"), ("absent", "ندارد")],
                        default="unknown",
                        max_length=8,
                    ),
                ),
                (
                    "balcony",
                    models.CharField(
                        choices=[("unknown", "نامشخص"), ("present", "دارد"), ("absent", "ندارد")],
                        default="unknown",
                        max_length=8,
                    ),
                ),
                (
                    "furnished",
                    models.CharField(
                        choices=[("unknown", "نامشخص"), ("present", "دارد"), ("absent", "ندارد")],
                        default="unknown",
                        max_length=8,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("contact_name", models.CharField(blank=True, max_length=120)),
                ("contact_phone", models.CharField(blank=True, max_length=32)),
                ("authorization_declared", models.BooleanField(default=False)),
                ("phone_publication_consent", models.BooleanField(default=False)),
                ("review_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.city",
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.district",
                    ),
                ),
                (
                    "neighborhood",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.neighborhood",
                    ),
                ),
                (
                    "submitter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at",),
            },
        ),
    ]
