# Generated by Django 6.1 on 2026-09-17 17:56

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.common.deletion
import apps.submissions.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("common", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("owner", "مالک"), ("agent", "نماینده مالک")], max_length=8
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "پیش\u200cنویس"),
                            ("pending", "در انتظار بررسی"),
                            ("changes_requested", "نیازمند اصلاح"),
                            ("rejected", "ردشده"),
                            ("published", "منتشرشده"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("revision", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "current_step",
                    models.CharField(
                        choices=[
                            ("location", "نشانی ملک"),
                            ("property_facts", "مشخصات ملک"),
                            ("rental_terms", "شرایط اجاره"),
                            ("features_description", "امکانات و توضیحات"),
                            ("images", "تصاویر"),
                            ("contact", "اطلاعات تماس"),
                            ("review", "بازبینی"),
                        ],
                        default="location",
                        max_length=32,
                    ),
                ),
                ("media_complete", models.BooleanField(default=False, editable=False)),
                ("address", models.TextField(blank=True)),
                (
                    "exact_latitude",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
                ),
                (
                    "exact_longitude",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
                ),
                (
                    "property_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("apartment", "آپارتمان"),
                            ("house", "خانه"),
                            ("villa", "ویلا"),
                            ("office", "دفتر اداری"),
                            ("shop", "مغازه"),
                            ("warehouse", "انبار"),
                            ("workshop", "کارگاه"),
                        ],
                        max_length=16,
                    ),
                ),
                ("area_sqm", models.PositiveIntegerField(blank=True, null=True)),
                ("room_count", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("construction_year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("floor", models.SmallIntegerField(blank=True, null=True)),
                ("total_floors", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("units_per_floor", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("deposit_rial", models.PositiveBigIntegerField(blank=True, null=True)),
                ("monthly_rent_rial", models.PositiveBigIntegerField(blank=True, null=True)),
                ("is_negotiable", models.BooleanField(default=False)),
                ("is_convertible", models.BooleanField(default=False)),
                (
                    "parking",
                    models.CharField(
                        choices=[("unknown", "نامشخص"), ("present", "دارد"), ("absent", "ندارد")],
                        default="unknown",
                        max_length=8,
                    ),
                ),
                (
                    "elevator",
                    models.CharField(
                        choices=[("unknown", "نامشخص"), ("present", "دارد"), ("absent", "ندارد")],
                        default="unknown",
                        max_length=8,
                    ),
                ),
                (
                    "storage",
                    models.CharField(
                        choices=[("unknown", "نامشخص"), ("present", "دارد"), ("absent", "ندارد")],
                        default="unknown",
                        max_length=8,
                    ),
                ),
                (
                    "balcony",
                    models.CharField(
                        choices=[("unknown", "نامشخص"), ("present", "دارد"), ("absent", "ندارد")],
                        default="unknown",
                        max_length=8,
                    ),
                ),
                (
                    "furnished",
                    models.CharField(
                        choices=[("unknown", "نامشخص"), ("present", "دارد"), ("absent", "ندارد")],
                        default="unknown",
                        max_length=8,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("contact_name", models.CharField(blank=True, max_length=120)),
                ("contact_phone", models.CharField(blank=True, max_length=32)),
                (
                    "contact_phone_source",
                    models.CharField(
                        choices=[
                            ("account", "شماره تأییدشده حساب"),
                            ("alternate", "شماره تأییدشده دیگر"),
                        ],
                        default="account",
                        max_length=16,
                    ),
                ),
                (
                    "alternate_contact_phone_verified_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("authorization_declared", models.BooleanField(default=False)),
                ("phone_publication_consent", models.BooleanField(default=False)),
                ("review_data", models.JSONField(blank=True, default=dict)),
                (
                    "pending_since",
                    models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
                ),
                ("discarded_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.city",
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.district",
                    ),
                ),
                (
                    "listing",
                    models.OneToOneField(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submission",
                        to="catalog.listing",
                    ),
                ),
                (
                    "neighborhood",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.neighborhood",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submissions",
                        to="catalog.source",
                    ),
                ),
                (
                    "submitter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at",),
                "permissions": (("review_submission", "Can review and publish Submissions"),),
            },
        ),
        migrations.CreateModel(
            name="ReviewClaim",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("revision", models.PositiveIntegerField()),
                ("expires_at", models.DateTimeField()),
                ("renewed_at", models.DateTimeField()),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("release_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submission_review_claims",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "released_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="released_submission_review_claims",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_claims",
                        to="submissions.submission",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="SubmissionContactVerificationChallenge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("phone", models.CharField(db_index=True, max_length=11)),
                ("secret_hash", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_verification_challenges",
                        to="submissions.submission",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubmissionEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("transition", "تغییر وضعیت"),
                            ("decision_correction", "اصلاح تصمیم"),
                        ],
                        default="transition",
                        max_length=24,
                    ),
                ),
                ("revision", models.PositiveIntegerField()),
                (
                    "prior_state",
                    models.CharField(
                        choices=[
                            ("draft", "پیش\u200cنویس"),
                            ("pending", "در انتظار بررسی"),
                            ("changes_requested", "نیازمند اصلاح"),
                            ("rejected", "ردشده"),
                            ("published", "منتشرشده"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "new_state",
                    models.CharField(
                        choices=[
                            ("draft", "پیش\u200cنویس"),
                            ("pending", "در انتظار بررسی"),
                            ("changes_requested", "نیازمند اصلاح"),
                            ("rejected", "ردشده"),
                            ("published", "منتشرشده"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("normalized_corrections", models.JSONField(blank=True, default=dict)),
                ("publication_result", models.JSONField(blank=True, default=dict)),
                ("correction", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=apps.common.deletion.set_null_in_immutable_history,
                        related_name="submission_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "corrects",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="corrections",
                        to="submissions.submissionevent",
                    ),
                ),
                (
                    "review_claim",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decision_events",
                        to="submissions.reviewclaim",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="submissions.submission",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="SubmissionDecisionNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار ارسال"),
                            ("delivered", "ارسال\u200cشده"),
                            ("failed", "ناموفق"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                (
                    "failure_kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("dispatch_failed", "صف ارسال در دسترس نبود"),
                            ("delivery_failed", "سرویس ایمیل پیام را نپذیرفت"),
                        ],
                        max_length=24,
                    ),
                ),
                ("last_error", models.CharField(blank=True, max_length=500)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decision",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notification",
                        to="submissions.submissionevent",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="SubmissionImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "source",
                    models.FileField(
                        blank=True,
                        max_length=500,
                        upload_to=apps.submissions.models.submission_image_upload_path,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در صف پردازش"),
                            ("processing", "در حال پردازش"),
                            ("ready", "آماده"),
                            ("failed", "ناموفق"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("failure_reason", models.CharField(blank=True, max_length=500)),
                ("position", models.PositiveSmallIntegerField()),
                ("is_primary", models.BooleanField(default=False)),
                ("raw_content_sha256", models.CharField(blank=True, max_length=64)),
                ("normalized_pixel_sha256", models.CharField(blank=True, max_length=64)),
                ("perceptual_dhash", models.CharField(blank=True, max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="submissions.submission",
                    ),
                ),
            ],
            options={
                "ordering": ("position", "created_at"),
            },
        ),
        migrations.CreateModel(
            name="SubmissionImageVariant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("small", "کوچک"), ("medium", "متوسط"), ("large", "بزرگ")],
                        max_length=8,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=500,
                        upload_to=apps.submissions.models.submission_image_variant_path,
                    ),
                ),
                ("width", models.PositiveIntegerField()),
                ("height", models.PositiveIntegerField()),
                ("byte_size", models.PositiveIntegerField()),
                (
                    "asset",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submission_variants",
                        to="common.mediaasset",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="submissions.submissionimage",
                    ),
                ),
            ],
            options={
                "ordering": ("width",),
            },
        ),
        migrations.AddConstraint(
            model_name="reviewclaim",
            constraint=models.UniqueConstraint(
                condition=models.Q(("released_at__isnull", True)),
                fields=("submission", "revision"),
                name="one_open_review_claim_per_submission_revision",
            ),
        ),
        migrations.AddIndex(
            model_name="submissioncontactverificationchallenge",
            index=models.Index(
                fields=["submission", "-created_at"], name="submissions_submiss_589477_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="submissionevent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("new_state", "pending")),
                fields=("submission", "revision", "new_state"),
                name="one_pending_transition_per_submission_revision",
            ),
        ),
        migrations.AddConstraint(
            model_name="submissionimage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("submission",),
                name="one_primary_image_per_submission",
            ),
        ),
        migrations.AddConstraint(
            model_name="submissionimage",
            constraint=models.UniqueConstraint(
                fields=("submission", "position"), name="unique_image_position_per_submission"
            ),
        ),
        migrations.AddConstraint(
            model_name="submissionimagevariant",
            constraint=models.UniqueConstraint(
                fields=("image", "kind"), name="unique_submission_image_variant"
            ),
        ),
    ]
