# Generated by Django 6.1 on 2026-08-22 11:44

import uuid

import django.db.models.deletion
from django.db import migrations, models

import apps.submissions.models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmissionImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "source",
                    models.FileField(
                        blank=True,
                        max_length=500,
                        upload_to=apps.submissions.models.submission_image_upload_path,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در صف پردازش"),
                            ("processing", "در حال پردازش"),
                            ("ready", "آماده"),
                            ("failed", "ناموفق"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("failure_reason", models.CharField(blank=True, max_length=500)),
                ("position", models.PositiveSmallIntegerField()),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="submissions.submission",
                    ),
                ),
            ],
            options={
                "ordering": ("position", "created_at"),
            },
        ),
        migrations.CreateModel(
            name="SubmissionImageVariant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("small", "کوچک"), ("medium", "متوسط"), ("large", "بزرگ")],
                        max_length=8,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=500,
                        upload_to=apps.submissions.models.submission_image_variant_path,
                    ),
                ),
                ("width", models.PositiveIntegerField()),
                ("height", models.PositiveIntegerField()),
                ("byte_size", models.PositiveIntegerField()),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="submissions.submissionimage",
                    ),
                ),
            ],
            options={
                "ordering": ("width",),
            },
        ),
        migrations.AddConstraint(
            model_name="submissionimage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("submission",),
                name="one_primary_image_per_submission",
            ),
        ),
        migrations.AddConstraint(
            model_name="submissionimage",
            constraint=models.UniqueConstraint(
                fields=("submission", "position"), name="unique_image_position_per_submission"
            ),
        ),
        migrations.AddConstraint(
            model_name="submissionimagevariant",
            constraint=models.UniqueConstraint(
                fields=("image", "kind"), name="unique_submission_image_variant"
            ),
        ),
    ]
