# Generated by Django 6.1 on 2026-08-22 16:45

import uuid

import django.db.models.deletion
from django.db import migrations, models


def create_assets_for_submission_variants(apps, _schema_editor):
    media_asset = apps.get_model("submissions", "MediaAsset")
    submission_variant = apps.get_model("submissions", "SubmissionImageVariant")
    assets_by_file = {
        asset.file: asset for asset in media_asset.objects.exclude(file="").iterator()
    }
    for variant in submission_variant.objects.exclude(file="").iterator():
        asset = assets_by_file.get(variant.file)
        if asset is None:
            asset = media_asset.objects.create(
                file=variant.file,
                width=variant.width,
                height=variant.height,
                byte_size=variant.byte_size,
            )
            assets_by_file[variant.file] = asset
        variant.asset = asset
        variant.save(update_fields=("asset",))


def detach_assets_from_submission_variants(apps, _schema_editor):
    submission_variant = apps.get_model("submissions", "SubmissionImageVariant")
    submission_variant.objects.update(asset=None)


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0002_submissionimage_submissionimagevariant_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file", models.FileField(max_length=500, unique=True, upload_to="")),
                ("width", models.PositiveIntegerField()),
                ("height", models.PositiveIntegerField()),
                ("byte_size", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="submissionimagevariant",
            name="asset",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="submission_variants",
                to="submissions.mediaasset",
            ),
        ),
        migrations.RunPython(
            create_assets_for_submission_variants,
            detach_assets_from_submission_variants,
        ),
    ]
