# Generated by Django 6.1 on 2026-08-22 17:08

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_listingimage_listingimagevariant_and_more"),
        ("submissions", "0003_share_processed_media_assets"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="submission",
            options={
                "ordering": ("-updated_at",),
                "permissions": (("review_submission", "Can review and publish Submissions"),),
            },
        ),
        migrations.AddField(
            model_name="submission",
            name="listing",
            field=models.OneToOneField(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="submission",
                to="catalog.listing",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="revision",
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name="submission",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="submissions",
                to="catalog.source",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="state",
            field=models.CharField(
                choices=[
                    ("draft", "پیش\u200cنویس"),
                    ("pending", "در انتظار بررسی"),
                    ("changes_requested", "نیازمند اصلاح"),
                    ("rejected", "ردشده"),
                    ("published", "منتشرشده"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="SubmissionEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("revision", models.PositiveIntegerField()),
                (
                    "prior_state",
                    models.CharField(
                        choices=[
                            ("draft", "پیش\u200cنویس"),
                            ("pending", "در انتظار بررسی"),
                            ("changes_requested", "نیازمند اصلاح"),
                            ("rejected", "ردشده"),
                            ("published", "منتشرشده"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "new_state",
                    models.CharField(
                        choices=[
                            ("draft", "پیش\u200cنویس"),
                            ("pending", "در انتظار بررسی"),
                            ("changes_requested", "نیازمند اصلاح"),
                            ("rejected", "ردشده"),
                            ("published", "منتشرشده"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submission_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="submissions.submission",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("new_state", "pending")),
                        fields=("submission", "revision", "new_state"),
                        name="one_pending_transition_per_submission_revision",
                    )
                ],
            },
        ),
    ]
