# Generated by Django 6.1 on 2026-08-25 09:25

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_current_pending_period(apps, schema_editor):
    Submission = apps.get_model("submissions", "Submission")
    SubmissionEvent = apps.get_model("submissions", "SubmissionEvent")
    for submission in Submission.objects.filter(state="pending").iterator():
        event = (
            SubmissionEvent.objects
            .filter(
                submission_id=submission.id,
                revision=submission.revision,
                new_state="pending",
            )
            .order_by("-created_at")
            .first()
        )
        submission.pending_since = event.created_at if event else submission.updated_at
        submission.save(update_fields=("pending_since",))


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0004_alter_submission_options_submission_listing_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="pending_since",
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.RunPython(backfill_current_pending_period, migrations.RunPython.noop),
        migrations.CreateModel(
            name="ReviewClaim",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("revision", models.PositiveIntegerField()),
                ("expires_at", models.DateTimeField()),
                ("renewed_at", models.DateTimeField()),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("release_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submission_review_claims",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "released_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="released_submission_review_claims",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_claims",
                        to="submissions.submission",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("released_at__isnull", True)),
                        fields=("submission", "revision"),
                        name="one_open_review_claim_per_submission_revision",
                    )
                ],
            },
        ),
    ]
