# Generated by Django 6.1 on 2026-08-25 11:26

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0006_submissionevent_decision_audit"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmissionDecisionNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار ارسال"),
                            ("delivered", "ارسال\u200cشده"),
                            ("failed", "ناموفق"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                (
                    "failure_kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("dispatch_failed", "صف ارسال در دسترس نبود"),
                            ("delivery_failed", "سرویس ایمیل پیام را نپذیرفت"),
                        ],
                        max_length=24,
                    ),
                ),
                ("last_error", models.CharField(blank=True, max_length=500)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decision",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notification",
                        to="submissions.submissionevent",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
