# Generated by Django 6.1 on 2026-08-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0007_submissiondecisionnotification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="property_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("apartment", "آپارتمان"),
                    ("house", "خانه"),
                    ("villa", "ویلا"),
                    ("office", "دفتر اداری"),
                ],
                max_length=16,
            ),
        ),
    ]
