# Generated by Django 6.1 on 2026-08-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0009_alter_submission_property_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="exact_latitude",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="exact_longitude",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
