# Generated by Django 6.1 on 2026-09-01 04:52

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0010_submission_exact_latitude_submission_exact_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="alternate_contact_phone_verified_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="contact_phone_source",
            field=models.CharField(
                choices=[("account", "شماره تأییدشده حساب"), ("alternate", "شماره تأییدشده دیگر")],
                default="account",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="SubmissionContactVerificationChallenge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("phone", models.CharField(db_index=True, max_length=11)),
                ("secret_hash", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_verification_challenges",
                        to="submissions.submission",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["submission", "-created_at"], name="submissions_submiss_589477_idx"
                    )
                ],
            },
        ),
    ]
