# Generated by Django 6.1 on 2026-09-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0011_submission_alternate_contact_phone_verified_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="discarded_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
