# Generated by Django 6.1 on 2026-09-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0014_move_media_asset_to_common"),
    ]

    operations = [
        migrations.AddField(
            model_name="submissionimage",
            name="normalized_pixel_sha256",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="submissionimage",
            name="perceptual_dhash",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="submissionimage",
            name="raw_content_sha256",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
