// Generated by `make api-client`; do not edit manually.
import type { components } from "@/lib/api/schema";

export type PropertyCategory = components["schemas"]["PropertyCategoryEnum"];
export type PropertyType = components["schemas"]["PropertyTypeEnum"];

export const propertyTypeLabels = {
  apartment: "آپارتمان",
  house: "خانه",
  villa: "ویلا",
  office: "دفتر اداری",
  shop: "مغازه",
  warehouse: "انبار",
  workshop: "کارگاه",
} as const satisfies Record<PropertyType, string>;

export const propertyTypeGroups = [
  {
    category: "residential",
    label: "مسکونی",
    types: ["apartment", "house", "villa"],
  },
  {
    category: "commercial",
    label: "تجاری",
    types: ["office", "shop", "warehouse", "workshop"],
  },
] as const satisfies readonly {
  category: PropertyCategory;
  label: string;
  types: readonly PropertyType[];
}[];

export const propertyTypeOptions = propertyTypeGroups.flatMap(({ types }) =>
  types.map((type) => [type, propertyTypeLabels[type]] as const),
);

export function propertyCategoryForType(type: PropertyType): PropertyCategory {
  const group = propertyTypeGroups.find(({ types }) =>
    (types as readonly PropertyType[]).includes(type),
  );
  if (!group) throw new Error(`Property Type ${type} has no Property Category`);
  return group.category;
}

export const roomCountLabels = {
  residential: { fact: "خواب", field: "تعداد اتاق خواب" },
  commercial: { fact: "اتاق", field: "تعداد اتاق یا پارتیشن" },
} as const satisfies Record<PropertyCategory, { fact: string; field: string }>;
