import { index, route, type RouteConfig } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("about", "routes/about.tsx"),
  route("guide", "routes/guide.tsx"),
  route("contact", "routes/contact.tsx"),
  route("login", "routes/login.tsx"),
  route("register", "routes/register.tsx"),
  route("advertise", "routes/advertise.tsx"),
  route("submitter/get-started", "routes/submitter-get-started.tsx"),
  route("forgot-password", "routes/forgot-password.tsx"),
  route("favorites", "routes/favorites-redirect.tsx"),
  route("dashboard/favorites", "routes/dashboard-favorites.tsx"),
  route("messages/*", "routes/legacy-messages.tsx"),
  route("dashboard/messages", "routes/messages.tsx"),
  route("dashboard/messages/new/support", "routes/support-composer.tsx"),
  route("dashboard/messages/:messageId", "routes/message-detail.tsx"),
  route("verify-email", "routes/verify-email.tsx"),
  route("reset-password", "routes/reset-password.tsx"),
  route("privacy", "routes/privacy.tsx"),
  route("terms", "routes/terms.tsx"),
  route("add-submission", "routes/protected-add-submission.tsx"),
  route("source-proposal", "routes/legacy-website.tsx"),
  route("dashboard/website", "routes/protected-source-proposal.tsx"),
  route("search", "routes/search.tsx"),
  route("properties/:propertyId/:slug?", "routes/property-detail.tsx"),
  route("dashboard/profile", "routes/submitter-profile.tsx"),
  route("dashboard", "routes/protected-dashboard.tsx"),
  route("operator", "routes/operator-layout.tsx", [
    index("pages/OperatorOverviewPage.tsx"),
    route("catalog-curation/:section?", "routes/operator-catalog-curation.tsx"),
    route("submissions", "routes/operator-submissions.tsx"),
    route("source-proposals", "routes/operator-source-proposals.tsx"),
    route(
      "source-proposals/:proposalId",
      "routes/operator-source-proposal-detail.tsx",
    ),
    route("external-listings", "routes/operator-external-listings.tsx"),
    route("support", "routes/operator-support.tsx"),
    route("conversation-reports", "routes/operator-conversation-reports.tsx"),
    route("review", "routes/operator-review-redirect.tsx"),
  ]),
] satisfies RouteConfig;
