import { index, route, type RouteConfig } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("about", "routes/about.tsx"),
  route("guide", "routes/guide.tsx"),
  route("contact", "routes/contact.tsx"),
  route("login", "routes/login.tsx"),
  route("register", "routes/register.tsx"),
  route("advertise", "routes/advertise.tsx"),
  route("submitter/get-started", "routes/submitter-get-started.tsx"),
  route("forgot-password", "routes/forgot-password.tsx"),
  route("favorites", "pages/FavoritesPage.tsx"),
  route("verify-email", "routes/verify-email.tsx"),
  route("reset-password", "routes/reset-password.tsx"),
  route("privacy", "routes/privacy.tsx"),
  route("terms", "routes/terms.tsx"),
  route("add-submission", "routes/protected-add-submission.tsx"),
  route("source-proposal", "routes/protected-source-proposal.tsx"),
  route("search", "pages/ResultsPage.tsx"),
  route("properties/:propertyId/:slug?", "routes/property-detail.tsx"),
  route("dashboard", "routes/protected-dashboard.tsx"),
  route("operator", "routes/operator-layout.tsx", [
    index("pages/OperatorOverviewPage.tsx"),
    route("submissions", "routes/operator-submissions.tsx"),
    route("support", "routes/operator-support.tsx"),
    route("links", "routes/operator-links.tsx"),
    route("review", "routes/operator-review-redirect.tsx"),
  ]),
] satisfies RouteConfig;
