# Generated by Django 6.1 on 2026-09-17 17:56

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("source_proposals", "0001_initial"),
        ("submissions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "originating_candidate_event",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="system_notifications",
                        to="source_proposals.externallistingcandidateevent",
                    ),
                ),
                (
                    "originating_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="system_notifications",
                        to="submissions.submissionevent",
                    ),
                ),
                (
                    "originating_run_decision",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="system_notifications",
                        to="source_proposals.extractionrundecision",
                    ),
                ),
                (
                    "originating_source_exception_notice",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notification",
                        to="source_proposals.sourceexceptionnotice",
                    ),
                ),
                (
                    "originating_source_proposal_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="system_notifications",
                        to="source_proposals.sourceproposalevent",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="system_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_source_proposal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="system_notifications",
                        to="source_proposals.sourceproposal",
                    ),
                ),
                (
                    "target_submission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="system_notifications",
                        to="submissions.submission",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="ConversationReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("reporter_display_name_snapshot", models.CharField(max_length=120)),
                (
                    "target_kind",
                    models.CharField(
                        choices=[("inquiry", "Inquiry"), ("message", "Message")], max_length=16
                    ),
                ),
                ("explanation", models.TextField(blank=True, max_length=2000)),
                ("evidence", models.JSONField(blank=True, null=True)),
                (
                    "evidence_retention_status",
                    models.CharField(
                        choices=[
                            ("investigation", "Investigation"),
                            ("required", "Required"),
                            ("released", "Released"),
                        ],
                        default="investigation",
                        max_length=16,
                    ),
                ),
                ("evidence_released_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("dismissed", "Dismissed"),
                            ("upheld", "Upheld"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("internal_note", models.TextField(blank=True, max_length=2000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decided_conversation_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversation_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
                "permissions": [
                    ("moderate_conversation_reports", "Can moderate Conversation Reports")
                ],
            },
        ),
        migrations.CreateModel(
            name="ConversationModerationEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("inspected", "Inspected"),
                            ("dismissed", "Dismissed"),
                            ("upheld", "Upheld"),
                            ("pair_restricted", "Pair restricted"),
                            ("initiation_suspended", "Initiation suspended"),
                            ("evidence_released", "Evidence released"),
                        ],
                        max_length=24,
                    ),
                ),
                ("internal_note", models.TextField(blank=True, max_length=2000)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conversation_moderation_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="moderation_events",
                        to="communications.conversationreport",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="InquiryInitiationSuspension",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inquiry_initiation_suspension",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_inquiry_initiation_suspensions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="initiation_suspensions",
                        to="communications.conversationreport",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ListingInquiry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("opening_property_title", models.CharField(editable=False, max_length=255)),
                ("opening_area_sqm", models.PositiveIntegerField(editable=False)),
                ("opening_deposit_rial", models.PositiveBigIntegerField(editable=False)),
                ("opening_monthly_rent_rial", models.PositiveBigIntegerField(editable=False)),
                ("opening_currency", models.CharField(default="IRR", editable=False, max_length=3)),
                ("opening_source_display_name", models.CharField(editable=False, max_length=120)),
                ("opening_message_fingerprint", models.CharField(editable=False, max_length=64)),
                ("renter_read_at", models.DateTimeField(blank=True, null=True)),
                ("submitter_read_at", models.DateTimeField(blank=True, null=True)),
                ("latest_activity_at", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "listing",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inquiries",
                        to="catalog.listing",
                    ),
                ),
                (
                    "renter",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="renter_listing_inquiries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitter",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitter_listing_inquiries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-latest_activity_at", "-id"),
            },
        ),
        migrations.AddField(
            model_name="conversationreport",
            name="inquiry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reports",
                to="communications.listinginquiry",
            ),
        ),
        migrations.CreateModel(
            name="ListingInquiryMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("body", models.TextField(max_length=2000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("edit_locked_at", models.DateTimeField(blank=True, editable=False, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="listing_inquiry_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inquiry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="communications.listinginquiry",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="ConversationReportEvidenceHold",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_holds",
                        to="communications.conversationreport",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conversation_report_evidence_holds",
                        to="communications.listinginquirymessage",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="conversationreport",
            name="target_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reports",
                to="communications.listinginquirymessage",
            ),
        ),
        migrations.CreateModel(
            name="ModeratedPairRestriction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_moderated_pair_restrictions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "higher_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderated_restrictions_as_higher",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lower_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderated_restrictions_as_lower",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pair_restriction",
                        to="communications.conversationreport",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SourceConversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("latest_activity_at", models.DateTimeField(db_index=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "proposal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conversation",
                        to="source_proposals.sourceproposal",
                    ),
                ),
            ],
            options={
                "ordering": ("-latest_activity_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="SourceConversationMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("from_representative", models.BooleanField()),
                ("body", models.TextField(max_length=2000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("redacted_at", models.DateTimeField(editable=False, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="messages",
                        to="communications.sourceconversation",
                    ),
                ),
                (
                    "redacted_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="redacted_source_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="SourceConversationReadState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("read_at", models.DateTimeField(null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="read_states",
                        to="communications.sourceconversation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SystemNotificationReadState",
            fields=[
                (
                    "notification",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="read_state",
                        serialize=False,
                        to="communications.systemnotification",
                    ),
                ),
                ("read_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="AccountBlock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_account_blocks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "higher_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_blocks_as_higher",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lower_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_blocks_as_lower",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("lower_account", "higher_account"),
                        name="one_account_block_per_pair",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("lower_account", models.F("higher_account")), _negated=True
                        ),
                        name="account_block_accounts_differ",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("created_by", models.F("lower_account")),
                            ("created_by", models.F("higher_account")),
                            _connector="OR",
                        ),
                        name="account_block_created_by_participant",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="listinginquiry",
            index=models.Index(
                fields=["renter", "opening_message_fingerprint", "created_at"],
                name="inquiry_repeated_content_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="listinginquiry",
            constraint=models.UniqueConstraint(
                fields=("renter", "listing"), name="one_listing_inquiry_per_renter_listing"
            ),
        ),
        migrations.AddConstraint(
            model_name="listinginquiry",
            constraint=models.CheckConstraint(
                condition=models.Q(("renter", models.F("submitter")), _negated=True),
                name="listing_inquiry_participants_differ",
            ),
        ),
        migrations.AddConstraint(
            model_name="conversationreportevidencehold",
            constraint=models.UniqueConstraint(
                fields=("report", "message"), name="one_evidence_hold_per_report_message"
            ),
        ),
        migrations.AddConstraint(
            model_name="moderatedpairrestriction",
            constraint=models.UniqueConstraint(
                fields=("lower_account", "higher_account"),
                name="one_moderated_restriction_per_pair",
            ),
        ),
        migrations.AddConstraint(
            model_name="moderatedpairrestriction",
            constraint=models.CheckConstraint(
                condition=models.Q(("lower_account", models.F("higher_account")), _negated=True),
                name="moderated_restriction_accounts_differ",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceconversationreadstate",
            constraint=models.UniqueConstraint(
                fields=("conversation", "account"), name="one_source_conversation_read_state"
            ),
        ),
        migrations.AddConstraint(
            model_name="systemnotification",
            constraint=models.UniqueConstraint(
                fields=("recipient", "originating_event"),
                name="one_system_notification_per_recipient_event",
            ),
        ),
        migrations.AddConstraint(
            model_name="systemnotification",
            constraint=models.UniqueConstraint(
                fields=("recipient", "originating_source_proposal_event"),
                name="one_system_notification_per_recipient_source_proposal_event",
            ),
        ),
        migrations.AddConstraint(
            model_name="systemnotification",
            constraint=models.UniqueConstraint(
                fields=("recipient", "originating_run_decision"),
                name="one_notification_per_run_decision",
            ),
        ),
        migrations.AddConstraint(
            model_name="systemnotification",
            constraint=models.UniqueConstraint(
                fields=("recipient", "originating_candidate_event"),
                name="one_notification_per_candidate_event",
            ),
        ),
        migrations.AddConstraint(
            model_name="systemnotification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("originating_candidate_event__isnull", True),
                        ("originating_event__isnull", False),
                        ("originating_run_decision__isnull", True),
                        ("originating_source_exception_notice__isnull", True),
                        ("originating_source_proposal_event__isnull", True),
                    ),
                    models.Q(
                        ("originating_candidate_event__isnull", True),
                        ("originating_event__isnull", True),
                        ("originating_run_decision__isnull", True),
                        ("originating_source_exception_notice__isnull", True),
                        ("originating_source_proposal_event__isnull", False),
                    ),
                    models.Q(
                        ("originating_candidate_event__isnull", True),
                        ("originating_event__isnull", True),
                        ("originating_run_decision__isnull", False),
                        ("originating_source_exception_notice__isnull", True),
                        ("originating_source_proposal_event__isnull", True),
                    ),
                    models.Q(
                        ("originating_candidate_event__isnull", False),
                        ("originating_event__isnull", True),
                        ("originating_run_decision__isnull", True),
                        ("originating_source_exception_notice__isnull", True),
                        ("originating_source_proposal_event__isnull", True),
                    ),
                    models.Q(
                        ("originating_candidate_event__isnull", True),
                        ("originating_event__isnull", True),
                        ("originating_run_decision__isnull", True),
                        ("originating_source_exception_notice__isnull", False),
                        ("originating_source_proposal_event__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="system_notification_has_exactly_one_originating_event",
            ),
        ),
    ]
