# Generated by Django 6.1 on 2026-09-03

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("submissions", "0012_submission_discarded_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "originating_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="system_notifications",
                        to="submissions.submissionevent",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="system_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_submission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="system_notifications",
                        to="submissions.submission",
                    ),
                ),
            ],
            options={"ordering": ("-created_at", "-id")},
        ),
        migrations.CreateModel(
            name="SystemNotificationReadState",
            fields=[
                (
                    "notification",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="read_state",
                        serialize=False,
                        to="communications.systemnotification",
                    ),
                ),
                ("read_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name="systemnotification",
            constraint=models.UniqueConstraint(
                fields=("recipient", "originating_event"),
                name="one_system_notification_per_recipient_event",
            ),
        ),
    ]
