# Generated by Django 6.1 on 2026-09-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemnotification",
            name="candidate_batch_event_ids",
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
    ]
