# Generated by Django 6.1 on 2026-09-03 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communications", "0001_initial"),
        (
            "source_proposals",
            "0006_remove_sourceproposal_one_open_source_proposal_per_account_domain_and_more",
        ),
        ("submissions", "0012_submission_discarded_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="systemnotification",
            name="originating_source_proposal_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="system_notifications",
                to="source_proposals.sourceproposalevent",
            ),
        ),
        migrations.AddField(
            model_name="systemnotification",
            name="target_source_proposal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="system_notifications",
                to="source_proposals.sourceproposal",
            ),
        ),
        migrations.AlterField(
            model_name="systemnotification",
            name="originating_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="system_notifications",
                to="submissions.submissionevent",
            ),
        ),
        migrations.AddConstraint(
            model_name="systemnotification",
            constraint=models.UniqueConstraint(
                fields=("recipient", "originating_source_proposal_event"),
                name="one_system_notification_per_recipient_source_proposal_event",
            ),
        ),
        migrations.AddConstraint(
            model_name="systemnotification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("originating_event__isnull", False),
                        ("originating_source_proposal_event__isnull", True),
                    ),
                    models.Q(
                        ("originating_event__isnull", True),
                        ("originating_source_proposal_event__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="system_notification_has_exactly_one_originating_event",
            ),
        ),
    ]
