# Generated by Django 6.1 on 2026-09-03 17:19

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0013_reduce_approximate_location_radius"),
        ("communications", "0002_systemnotification_originating_source_proposal_event_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ListingInquiry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("renter_read_at", models.DateTimeField(blank=True, null=True)),
                ("submitter_read_at", models.DateTimeField(blank=True, null=True)),
                ("latest_activity_at", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "listing",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inquiries",
                        to="catalog.listing",
                    ),
                ),
                (
                    "renter",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="renter_listing_inquiries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitter",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submitter_listing_inquiries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-latest_activity_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="ListingInquiryMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("body", models.TextField(max_length=2000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="listing_inquiry_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inquiry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="communications.listinginquiry",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.AddConstraint(
            model_name="listinginquiry",
            constraint=models.UniqueConstraint(
                fields=("renter", "listing"), name="one_listing_inquiry_per_renter_listing"
            ),
        ),
        migrations.AddConstraint(
            model_name="listinginquiry",
            constraint=models.CheckConstraint(
                condition=models.Q(("renter", models.F("submitter")), _negated=True),
                name="listing_inquiry_participants_differ",
            ),
        ),
    ]
