# Generated by Django 6.1 on 2026-09-03 19:00

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communications", "0006_listing_inquiry_repeated_content"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountBlock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_account_blocks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lower_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="account_blocks_as_lower",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "higher_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="account_blocks_as_higher",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("lower_account", "higher_account"),
                        name="one_account_block_per_pair",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("lower_account", models.F("higher_account")), _negated=True
                        ),
                        name="account_block_accounts_differ",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("created_by", models.F("lower_account")),
                            ("created_by", models.F("higher_account")),
                            _connector="OR",
                        ),
                        name="account_block_created_by_participant",
                    ),
                ],
            },
        ),
    ]
