# Generated by Django 6.1 on 2026-09-03 19:44

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_conversation_moderator_group(apps, schema_editor):
    content_type_model = apps.get_model("contenttypes", "ContentType")
    group_model = apps.get_model("auth", "Group")
    permission_model = apps.get_model("auth", "Permission")
    content_type, _ = content_type_model.objects.get_or_create(
        app_label="communications",
        model="conversationreport",
    )
    permission, _ = permission_model.objects.get_or_create(
        content_type=content_type,
        codename="moderate_conversation_reports",
        defaults={"name": "Can moderate Conversation Reports"},
    )
    group, _ = group_model.objects.get_or_create(name="Conversation Moderator")
    group.permissions.add(permission)


def remove_conversation_moderator_group(apps, schema_editor):
    group_model = apps.get_model("auth", "Group")
    group_model.objects.filter(name="Conversation Moderator").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("communications", "0007_accountblock"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("explanation", models.TextField(blank=True, max_length=2000)),
                ("evidence", models.JSONField(blank=True, null=True)),
                ("reporter_display_name_snapshot", models.CharField(max_length=120)),
                (
                    "target_kind",
                    models.CharField(
                        choices=[("inquiry", "Inquiry"), ("message", "Message")],
                        max_length=16,
                    ),
                ),
                (
                    "evidence_retention_status",
                    models.CharField(
                        choices=[
                            ("investigation", "Investigation"),
                            ("required", "Required"),
                            ("released", "Released"),
                        ],
                        default="investigation",
                        max_length=16,
                    ),
                ),
                ("evidence_released_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("dismissed", "Dismissed"),
                            ("upheld", "Upheld"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("internal_note", models.TextField(blank=True, max_length=2000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decided_conversation_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inquiry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reports",
                        to="communications.listinginquiry",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conversation_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reports",
                        to="communications.listinginquirymessage",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
                "permissions": [
                    ("moderate_conversation_reports", "Can moderate Conversation Reports")
                ],
            },
        ),
        migrations.CreateModel(
            name="ConversationReportEvidenceHold",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conversation_report_evidence_holds",
                        to="communications.listinginquirymessage",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_holds",
                        to="communications.conversationreport",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("report", "message"),
                        name="one_evidence_hold_per_report_message",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ConversationModerationEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("inspected", "Inspected"),
                            ("dismissed", "Dismissed"),
                            ("upheld", "Upheld"),
                            ("pair_restricted", "Pair restricted"),
                            ("initiation_suspended", "Initiation suspended"),
                            ("evidence_released", "Evidence released"),
                        ],
                        max_length=24,
                    ),
                ),
                ("internal_note", models.TextField(blank=True, max_length=2000)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conversation_moderation_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="moderation_events",
                        to="communications.conversationreport",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="InquiryInitiationSuspension",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inquiry_initiation_suspension",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_inquiry_initiation_suspensions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="initiation_suspensions",
                        to="communications.conversationreport",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModeratedPairRestriction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_moderated_pair_restrictions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "higher_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="moderated_restrictions_as_higher",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lower_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="moderated_restrictions_as_lower",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pair_restriction",
                        to="communications.conversationreport",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("lower_account", "higher_account"),
                        name="one_moderated_restriction_per_pair",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("lower_account", models.F("higher_account")), _negated=True
                        ),
                        name="moderated_restriction_accounts_differ",
                    ),
                ],
            },
        ),
        migrations.RunPython(
            create_conversation_moderator_group,
            remove_conversation_moderator_group,
        ),
    ]
