# Generated by Django 6.1 on 2026-09-05 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communications", "0009_apply_communication_retention"),
        ("source_proposals", "0013_extractionrundecision_and_more"),
        ("submissions", "0014_move_media_asset_to_common"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="systemnotification",
            name="system_notification_has_exactly_one_originating_event",
        ),
        migrations.AddField(
            model_name="systemnotification",
            name="originating_candidate_event",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="system_notifications",
                to="source_proposals.externallistingcandidateevent",
            ),
        ),
        migrations.AddField(
            model_name="systemnotification",
            name="originating_run_decision",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="system_notifications",
                to="source_proposals.extractionrundecision",
            ),
        ),
        migrations.AddConstraint(
            model_name="systemnotification",
            constraint=models.UniqueConstraint(
                fields=("recipient", "originating_run_decision"),
                name="one_notification_per_run_decision",
            ),
        ),
        migrations.AddConstraint(
            model_name="systemnotification",
            constraint=models.UniqueConstraint(
                fields=("recipient", "originating_candidate_event"),
                name="one_notification_per_candidate_event",
            ),
        ),
        migrations.AddConstraint(
            model_name="systemnotification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("originating_candidate_event__isnull", True),
                        ("originating_event__isnull", False),
                        ("originating_run_decision__isnull", True),
                        ("originating_source_proposal_event__isnull", True),
                    ),
                    models.Q(
                        ("originating_candidate_event__isnull", True),
                        ("originating_event__isnull", True),
                        ("originating_run_decision__isnull", True),
                        ("originating_source_proposal_event__isnull", False),
                    ),
                    models.Q(
                        ("originating_candidate_event__isnull", True),
                        ("originating_event__isnull", True),
                        ("originating_run_decision__isnull", False),
                        ("originating_source_proposal_event__isnull", True),
                    ),
                    models.Q(
                        ("originating_candidate_event__isnull", False),
                        ("originating_event__isnull", True),
                        ("originating_run_decision__isnull", True),
                        ("originating_source_proposal_event__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="system_notification_has_exactly_one_originating_event",
            ),
        ),
    ]
