# Generated by Django 6.1 on 2026-09-06 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communications", "0011_sourceconversation_sourceconversationmessage_and_more"),
        ("source_proposals", "0036_sourceexceptionnotificationstate_and_more"),
        ("submissions", "0014_move_media_asset_to_common"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="systemnotification",
            name="system_notification_has_exactly_one_originating_event",
        ),
        migrations.AddField(
            model_name="systemnotification",
            name="originating_source_exception_notice",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="notification",
                to="source_proposals.sourceexceptionnotice",
            ),
        ),
        migrations.AddConstraint(
            model_name="systemnotification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("originating_candidate_event__isnull", True),
                        ("originating_event__isnull", False),
                        ("originating_run_decision__isnull", True),
                        ("originating_source_exception_notice__isnull", True),
                        ("originating_source_proposal_event__isnull", True),
                    ),
                    models.Q(
                        ("originating_candidate_event__isnull", True),
                        ("originating_event__isnull", True),
                        ("originating_run_decision__isnull", True),
                        ("originating_source_exception_notice__isnull", True),
                        ("originating_source_proposal_event__isnull", False),
                    ),
                    models.Q(
                        ("originating_candidate_event__isnull", True),
                        ("originating_event__isnull", True),
                        ("originating_run_decision__isnull", False),
                        ("originating_source_exception_notice__isnull", True),
                        ("originating_source_proposal_event__isnull", True),
                    ),
                    models.Q(
                        ("originating_candidate_event__isnull", False),
                        ("originating_event__isnull", True),
                        ("originating_run_decision__isnull", True),
                        ("originating_source_exception_notice__isnull", True),
                        ("originating_source_proposal_event__isnull", True),
                    ),
                    models.Q(
                        ("originating_candidate_event__isnull", True),
                        ("originating_event__isnull", True),
                        ("originating_run_decision__isnull", True),
                        ("originating_source_exception_notice__isnull", False),
                        ("originating_source_proposal_event__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="system_notification_has_exactly_one_originating_event",
            ),
        ),
    ]
